### ISSUE TITLE
Cannot add anything through LG Thinq App

### ISSUE THREAD

**Issue by leonardpitzu** [t0bst4r/home-assistant-matter-hub#101]
trying to add the `switch` to my LG smart TV using the Thinq app and it cannot connect to the “device”

```
[ 2024-11-09T19:50:59.723Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: vethd87b70d
[ 2024-11-09T19:50:59.736Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: veth28b592b
[ 2024-11-09T19:50:59.740Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: veth84877dd
[ 2024-11-09T19:50:59.742Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: veth868c250
[ 2024-11-09T19:50:59.745Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: veth1084f44
[ 2024-11-09T19:50:59.748Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: vethbeb850e
[ 2024-11-09T19:50:59.751Z ] [ DEBUG ] [ matter.js / MdnsServer                             ]: Expiring records instanceName: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 netInterface: vethefa07a3
[ 2024-11-09T19:50:59.777Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: enp0s3
[ 2024-11-09T19:50:59.778Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: hassio
[ 2024-11-09T19:50:59.779Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: docker0
[ 2024-11-09T19:50:59.780Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth579d3ba
[ 2024-11-09T19:50:59.780Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth8292db7
[ 2024-11-09T19:50:59.781Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth4045c0f
[ 2024-11-09T19:50:59.782Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethfc2d640
[ 2024-11-09T19:50:59.783Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethd87b70d
[ 2024-11-09T19:50:59.784Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth28b592b
[ 2024-11-09T19:50:59.786Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth84877dd
[ 2024-11-09T19:50:59.787Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth868c250
[ 2024-11-09T19:50:59.787Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth1084f44
[ 2024-11-09T19:50:59.788Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethbeb850e
[ 2024-11-09T19:50:59.790Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethefa07a3
[ 2024-11-09T19:50:59.823Z ] [ DEBUG ] [ WebApi / access-log                                ]: GET /api/matter/bridges/877baf112a4f4c058062dadd27975846/devices?_s=1731181855727 200 OK
[ 2024-11-09T19:50:59.853Z ] [ DEBUG ] [ matter.js / MdnsScanner                            ]: Adding operational device AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local in cache (interface enp0s3, ttl=120) with TXT data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
[ 2024-11-09T19:50:59.939Z ] [ DEBUG ] [ matter.js / MdnsScanner                            ]: Removing operational device AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local from cache (interface enp0s3) because of ttl=0
[ 2024-11-09T19:50:59.954Z ] [ DEBUG ] [ matter.js / MdnsScanner                            ]: Adding operational device AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local in cache (interface enp0s3, ttl=120) with TXT data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
[ 2024-11-09T19:51:00.006Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: enp0s3
[ 2024-11-09T19:51:00.007Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: hassio
[ 2024-11-09T19:51:00.007Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: docker0
[ 2024-11-09T19:51:00.008Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth579d3ba
[ 2024-11-09T19:51:00.009Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth8292db7
[ 2024-11-09T19:51:00.010Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth4045c0f
[ 2024-11-09T19:51:00.011Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethfc2d640
[ 2024-11-09T19:51:00.012Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethd87b70d
[ 2024-11-09T19:51:00.013Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth28b592b
[ 2024-11-09T19:51:00.014Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth84877dd
[ 2024-11-09T19:51:00.015Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth868c250
[ 2024-11-09T19:51:00.016Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth1084f44
[ 2024-11-09T19:51:00.016Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethbeb850e
[ 2024-11-09T19:51:00.017Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethefa07a3
[ 2024-11-09T19:51:00.047Z ] [ DEBUG ] [ matter.js / DeviceAdvertiser                       ]: Resubmission started, re-announce node 16467143553149243887
[ 2024-11-09T19:51:00.048Z ] [ DEBUG ] [ matter.js / DeviceAdvertiser                       ]: Announcing fabric: 135393097
[ 2024-11-09T19:51:00.049Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Resubmit message 59268951 (retransmission attempt 1, backoff time 356ms))
[ 2024-11-09T19:51:00.050Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Message Â» id: 55017/7841/59268951 type: 1/1 acked: undefined reqAck: true duplicate: false payload: 1524000124ff0c18
[ 2024-11-09T19:51:00.066Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: enp0s3
[ 2024-11-09T19:51:00.067Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: hassio
[ 2024-11-09T19:51:00.067Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: docker0
[ 2024-11-09T19:51:00.068Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth579d3ba
[ 2024-11-09T19:51:00.069Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth8292db7
[ 2024-11-09T19:51:00.070Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth4045c0f
[ 2024-11-09T19:51:00.071Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethfc2d640
[ 2024-11-09T19:51:00.071Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethd87b70d
[ 2024-11-09T19:51:00.072Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth28b592b
[ 2024-11-09T19:51:00.073Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth84877dd
[ 2024-11-09T19:51:00.074Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth868c250
[ 2024-11-09T19:51:00.075Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: veth1084f44
[ 2024-11-09T19:51:00.075Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethbeb850e
[ 2024-11-09T19:51:00.076Z ] [ DEBUG ] [ matter.js / MdnsBroadcaster                        ]: Announcement Generator: Fabric id: aeadb4ab1f7068c5/1198159275 qname: AEADB4AB1F7068C5-00000000476A75AB._matter._tcp.local port: 5540 interface: vethefa07a3
[ 2024-11-09T19:51:00.240Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Cannot find a session for ID 60189
  at ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:165:13)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:334:16
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/net/UdpInterface.js:29:52
  at Socket.messageListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/net/NodeJsUdpChannel.js:111:7)
  at Socket.emit (node:events:517:28)
  at UDP.onMessage [as onmessage] (node:dgram:942:8)
[ 2024-11-09T19:51:00.330Z ] [ DEBUG ] [ WebApi / access-log                                ]: GET /api/matter/bridges/877baf112a4f4c058062dadd27975846/devices?_s=1731181846549 200 OK
[ 2024-11-09T19:51:00.408Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Resubmit message 59268951 (retransmission attempt 2, backoff time 598ms))
[ 2024-11-09T19:51:00.409Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Message Â» id: 55017/7841/59268951 type: 1/1 acked: undefined reqAck: true duplicate: false payload: 1524000124ff0c18
[ 2024-11-09T19:51:00.420Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Cannot find a session for ID 60189
  at ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:165:13)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:334:16
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/net/UdpInterface.js:29:52
  at Socket.messageListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/net/NodeJsUdpChannel.js:111:7)
  at Socket.emit (node:events:517:28)
  at UDP.onMessage [as onmessage] (node:dgram:942:8)
[ 2024-11-09T19:51:01.011Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Resubmit message 59268951 (retransmission attempt 3, backoff time 923ms))
[ 2024-11-09T19:51:01.012Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Message Â» id: 55017/7841/59268951 type: 1/1 acked: undefined reqAck: true duplicate: false payload: 1524000124ff0c18
[ 2024-11-09T19:51:01.020Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Cannot find a session for ID 60189
  at ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:165:13)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:334:16
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/net/UdpInterface.js:29:52
  at Socket.messageListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/net/NodeJsUdpChannel.js:111:7)
  at Socket.emit (node:events:517:28)
  at UDP.onMessage [as onmessage] (node:dgram:942:8)
[ 2024-11-09T19:51:01.938Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Resubmit message 59268951 (retransmission attempt 4, backoff time 1589ms))
[ 2024-11-09T19:51:01.941Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Message Â» id: 55017/7841/59268951 type: 1/1 acked: undefined reqAck: true duplicate: false payload: 1524000124ff0c18
[ 2024-11-09T19:51:01.948Z ] [ DEBUG ] [ matter.js / ExchangeManager                        ]: Cannot find a session for ID 60189
  at ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:165:13)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:334:16
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/net/UdpInterface.js:29:52
  at Socket.messageListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/net/NodeJsUdpChannel.js:111:7)
  at Socket.emit (node:events:517:28)
  at UDP.onMessage [as onmessage] (node:dgram:942:8)
[ 2024-11-09T19:51:03.532Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Wait additional 4640ms for processing time and peer resubmissions after all our resubmissions
[ 2024-11-09T19:51:05.078Z ] [ DEBUG ] [ WebApi / access-log                                ]: GET /api/matter/bridges/877baf112a4f4c058062dadd27975846/devices?_s=1731181864908 200 OK
[ 2024-11-09T19:51:08.176Z ] [ ERROR ] [ matter.js / ExchangeManager                        ]: RetransmissionLimitReachedError
  at #retransmitMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/MessageExchange.js:382:37)
  at StandardTimer.callback (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/MessageExchange.js:375:42)
  at Timeout._onTimeout (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/time/Time.js:109:12)
  at listOnTimeout (node:internal/timers:569:17)
  at process.processTimers (node:internal/timers:512:7)
[ 2024-11-09T19:51:12.649Z ] [ INFO  ] [ matter.js / ExchangeManager                        ]: Exchange with index 7841 to delete not found or already deleted. 
```

**Comment by t0bst4r** [comment]
I am using `matter.js` as a basis for this project. They have a list of supported devices for each ecosystem, and it seems that LG Thinq does not support bridges at all:

https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#device-types-tested-on-various-ecosystems

**Comment by leonardpitzu** [comment]
Oh, wow, thanks LG… Interesting that the old hub used to work. Not perfect but to some extent. Anyways, unless LG does something case is closed.
