### ISSUE TITLE
[Bug] addon crashes with error in climate-control

### ISSUE THREAD

**Issue by aebgit** [t0bst4r/home-assistant-matter-hub#103]
Since alpha-25 the addon crashes on boot with the following log:

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing d6b0f3aeb2aa425bab69f4dae9d6179c.aggregator.climate_wz_heizung.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating d6b0f3aeb2aa425bab69f4dae9d6179c.aggregator.climate_wz_heizung.thermostat.state: Conformance "HEAT": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as occupiedHeatingSetpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at Function.assign (<anonymous>)
        at ThermostatServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2262:16)
s6-rc: info: service legacy-services: stopping
```

Kind regards
Aebgit

**Comment by DJBenson** [comment]
This is still happening in alpha-26.

**Comment by t0bst4r** [comment]
This is more or less happening since alpha 19. we are still working on it: 
#73
