### ISSUE TITLE
Alfa.25 crash

### ISSUE THREAD

**Issue by myevit** [t0bst4r/home-assistant-matter-hub#106]
home-assistant-matter-hub start
start the application
Options:
  --help                         Show help                             [boolean]
  --log-level
  [string] [choices: "silly", "debug", "info", "warn", "error"] [default: "info"
                                                                               ]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --mdns-network-interface       Limit MDNS to this network interface   [string]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 041d03c8234d4690a3cba8e0277c870a.aggregator.climate_thermostat.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 041d03c8234d4690a3cba8e0277c870a.aggregator.climate_thermostat.thermostat.state: Conformance "HEAT": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as occupiedHeatingSetpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at Function.assign (<anonymous>)
        at ThermostatServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2262:16)
s6

**Comment by t0bst4r** [comment]
Climates are currently buggy / broken. We are actively working on them (#73).

**Comment by myevit** [comment]
Thanks. FYI Alfa.24 is working fine for me.
