### ISSUE TITLE
All devices offline

### ISSUE THREAD

**Issue by kevinvanhooren** [t0bst4r/home-assistant-matter-hub#125]
Hello,

First of all thanks for the great effort in this add-on. It will open doors for a lot of people.
In my case not everything works.
I've installed the add-on in HA and created a bridge.
Added the bridge in the Google Home app and is connected. All devices are added.
But they all show offline. Is there something I need to do extra?

Piece of the log:
[ 2024-11-12T16:11:22.161Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_outdoor_temperature.homeAssistant.state: Error in reactor<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_outdoor_temperature.temperatureMeasurement.update>: reactor<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_outdoor_temperature.temperatureMeasurement.update> returned a Promise but the observable is synchronous; you must set the "offline" option so this reactor runs with a dedicated transaction
  at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:194:15)
  at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:98:35)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/Behavior.js:170:36
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at ObservableProxy.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:332:30)
[ 2024-11-12T16:11:22.161Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction setStateOf<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature>#1bbb locked 607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature.homeAssistant.state and 607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature.temperatureMeasurement.state
[ 2024-11-12T16:11:22.161Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature.homeAssistant.state: Error in reactor<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature.temperatureMeasurement.update>: reactor<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature.temperatureMeasurement.update> returned a Promise but the observable is synchronous; you must set the "offline" option so this reactor runs with a dedicated transaction
  at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:194:15)
  at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:98:35)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/Behavior.js:170:36
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at ObservableProxy.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:332:30)
[ 2024-11-12T16:11:22.161Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction setStateOf<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_outdoor_temperature>#1bba committed and unlocked 2 resources
[ 2024-11-12T16:11:22.162Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction setStateOf<607701ddb5b540beb24791760761cac2.aggregator.sensor_brugge_circuit_0_current_flow_temperature>#1bbb committed and unlocked 2 resources

**Comment by kevinvanhooren** [comment]
Would it have something to do with this debig line?

[ 2024-11-12T16:43:27.475Z ] [ DEBUG ] [ matter.js / UdpChannelNode                         ]: Socket created and bound remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353

**Comment by t0bst4r** [comment]
No, it’s because this function is async but it shouldn’t and doesn’t need to:

https://github.com/t0bst4r/home-assistant-matter-hub/blob/a00419484f09dbaceadc3ae8fee74f9cea13b965/packages/backend/src/matter/behaviors/temperature-measurement-server.ts#L25

I am currently not at the computer, so I’ll fix it with highest priority later today, or tomorrow.

**Comment by kevinvanhooren** [comment]
No problem. Many thanks on advance!

**Comment by t0bst4r** [comment]
This should have been fixed with alpha.30. Anyway there is another bug preventing the app to boot. I am working on it.

**Comment by ronluna** [comment]
Having the same issue on latest alpha [v3.0.0-alpha.60]
