### ISSUE TITLE
input.boolean "Failed to Fetch"

### ISSUE THREAD

**Issue by andredts** [t0bst4r/home-assistant-matter-hub#126]
On Alexa, when trying to switch a boolean item I get it to change but get a erro "item is not responding", on the web interface I get a:
![image](https://github.com/user-attachments/assets/745010e3-b70a-486c-be8d-e1c04ec02f83)

on the log is like the bridge got rebooted:
```
           ^
SynchronousTransactionConflictError: Cannot lock 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.onOff.state synchronously
    at ResourceSet.acquireLocksSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/ResourceSet.js:66:13)
    at Tx.beginSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:198:32)
    at startWrite (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:192:17)
    at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:145:7)
    at OnOff$State.set [as onOff] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
    at OnOffServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1179:28)
    at #reactWithLocks (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:286:26)
    at #reactWithContext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:262:32)
    at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:192:44)
    at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:98:35)
Node.js v18.20.4
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Home-Assistant-Matter-Hub
 Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
-----------------------------------------------------------
 Add-on version: 3.0.0-alpha.28
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.11.1
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-11-12T18:02:14.984Z ] [ INFO  ] [ Storage                                            ]: Storage location: /config/data
[ 2024-11-12T18:02:15.274Z ] [ INFO  ] [ matter.js / ServerNodeStore                        ]: Opened 693312ca0f3e4900a507ab828b95e735 storage at /config/data/693312ca0f3e4900a507ab828b95e735
[ 2024-11-12T18:02:15.281Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 284851514429848961 and peer node 284851514429848961 for fabric index 1
[ 2024-11-12T18:02:15.919Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions 💤controller ✔descriptor
[ 2024-11-12T18:02:15.933Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✔index ✔descriptor
[ 2024-11-12T18:02:15.972Z ] [ INFO  ] [ matter.js / Node                                   ]: 693312ca0f3e4900a507ab828b95e735 going online
[ 2024-11-12T18:02:16.339Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_sanca_estar ready endpoint#: 2 type: ExtendedColorLight (0x10d) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔colorControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.369Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_balcao ready endpoint#: 3 type: DimmableLight (0x101) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.519Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_retro ready endpoint#: 4 type: ColorTemperatureLight (0x10c) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔colorControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.567Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_color4 ready endpoint#: 5 type: ExtendedColorLight (0x10d) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔colorControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.611Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_cama_lais ready endpoint#: 6 type: ExtendedColorLight (0x10d) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔colorControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.659Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_rgb_strip ready endpoint#: 7 type: ExtendedColorLight (0x10d) behaviors: ✔identify ✔groups ✔onOff ✔levelControl ✔colorControl ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.685Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_musica_varanda ready endpoint#: 28 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:16.983Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.climate_split_escritorio ready endpoint#: 8 type: Thermostat (0x301) behaviors: ✔identify ✔bridgedDeviceBasicInformation ✔homeAssistant ✔relativeHumidityMeasurement ✔temperatureMeasurement ✔thermostat ✔descriptor
[ 2024-11-12T18:02:17.007Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_centro_l6 ready endpoint#: 9 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.029Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_entrada_l3 ready endpoint#: 10 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.051Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_centro_l1 ready endpoint#: 11 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.072Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_centro_l4 ready endpoint#: 12 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.095Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_entrada_l2 ready endpoint#: 13 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.128Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_entrada_l6 ready endpoint#: 14 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.154Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_centro_l5 ready endpoint#: 15 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.175Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_entrada_l4 ready endpoint#: 16 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.196Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_entrada_l5 ready endpoint#: 17 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.227Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_corredor_l1 ready endpoint#: 18 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.247Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_corredor_l2 ready endpoint#: 19 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.281Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_modulo_l3 ready endpoint#: 20 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.315Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_relayatv0_6_32_2 ready endpoint#: 21 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.339Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_relayatv0_6_32_1 ready endpoint#: 22 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.377Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_lavabo_center ready endpoint#: 24 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.399Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_lavabo_left ready endpoint#: 25 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.421Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_modulo_l1 ready endpoint#: 26 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.442Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.light_modulo_l2 ready endpoint#: 27 type: OnOffLight (0x100) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.464Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala ready endpoint#: 29 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ 2024-11-12T18:02:17.484Z ] [ INFO  ] [ WebApi                                             ]: HTTP server (API & Web App) listening on port 8482
[ 2024-11-12T18:02:17.551Z ] [ INFO  ] [ matter.js / Node                                   ]: 693312ca0f3e4900a507ab828b95e735 is online
[ 2024-11-12T18:02:17.558Z ] [ INFO  ] [ matter.js / AccessControlServer                    ]: initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 18446744060825763882, 18446744060824715265 ], targets: null, fabricIndex: 1 }
[ 2024-11-12T18:02:17.701Z ] [ INFO  ] [ matter.js / CaseServer                             ]: Received pairing request from udp://192.168.1.126:5541
[ 2024-11-12T18:02:17.730Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.homeAssistant.state: Error in reactor<693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.onOff.update>: reactor<693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.onOff.update> returned a Promise but the observable is synchronous; you must set the "offline" option so this reactor runs with a dedicated transaction
  at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:194:15)
  at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:98:35)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/Behavior.js:170:36
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at ObservableProxy.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:332:30)
[ 2024-11-12T18:02:17.771Z ] [ INFO  ] [ matter.js / CaseServer                             ]: session 57312 resumed with udp://192.168.1.126:5541 for Fabric 03F9F5B602627D40(index 1) and PeerNode 03F3FEF17352BD81 with CATs 1114154
[ 2024-11-12T18:02:17.774Z ] [ INFO  ] [ matter.js / InsecureSession                        ]: End insecure session insecure/9859076642587292040
[ 2024-11-12T18:02:17.784Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.onOff.off online#2c6bfba@3f3fef17352bd81 (no payload)
[ 2024-11-12T18:02:17.789Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke 693312ca0f3e4900a507ab828b95e735.aggregator.input_boolean_b_tv_sala.onOff.off online#2c6bfbb@3f3fef17352bd81 (no payload)
[ 2024-11-12T18:04:12.397Z ] [ INFO  ] [ matter.js / CaseServer                             ]: Received pairing request from udp://192.168.1.126:5541
[ 2024-11-12T18:04:12.424Z ] [ INFO  ] [ matter.js / CaseServer                             ]: session 57313 resumed with udp://192.168.1.126:5541 for Fabric 03F9F5B602627D40(index 1) and PeerNode 03F3FEF17352BD81 with CATs 1114154
[ 2024-11-12T18:04:12.429Z ] [ INFO  ] [ matter.js / InsecureSession                        ]: End insecure session insecure/16277977632084660391
[ 2024-11-12T18:04:15.264Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Successfully created subscription 2064300324 for Session 57313. Updates: 1 - 300 => 188 seconds (sendInterval = 94 seconds)
```

**Comment by t0bst4r** [comment]
this should be fixed with alpha.31.
