### ISSUE TITLE
Issue with colorControl attribute for Matter-compatible light device causing initialization failure

### ISSUE THREAD

**Issue by steuerlexi** [t0bst4r/home-assistant-matter-hub#133]
I'm experiencing an error with the home-assistant-matter-hub add-on when trying to initialize a Matter-compatible light device. This issue appears to be related to the colorControl attribute, which fails to initialize due to an HS (hue and saturation) conformance requirement.

**System Information:**

Add-on version: 3.0.0-alpha.29 (latest)
System: Home Assistant OS 13.2 (amd64 / qemux86-64)
Home Assistant Core: 2024.11.1
Home Assistant Supervisor: 2024.11.3

`[ INFO  ] [ matter.js / Endpoint ]: <anonymous_id>.aggregator.light_awtrix_matrix ready endpoint#: 70 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔homeAssistant ✔descriptor
[ ERROR ] [ matter.js / Transaction ]: Rolling back initialize<anonymous_id.aggregator.light_awtrix_matrix>#c9 due to error: Behaviors have errors

Caused by: Validating <anonymous_id>.aggregator.light_awtrix_matrix.colorControl.state: Conformance "HS": Matter requires you to set this attribute (128)`

**Steps to Reproduce:**

Install and configure home-assistant-matter-hub add-on version 3.0.0-alpha.29.
Add a Matter-compatible light device (light_awtrix_matrix in this case) with color control capabilities.
Attempt to initialize the device.
Observe the error in logs related to colorControl attribute conformance.
Expected Behavior: The light device should initialize without errors, with Matter-compliant attributes for color control (hue/saturation) being applied correctly.

**Observed Behavior:** The initialization fails due to a missing HS conformance attribute for colorControl, resulting in a rollback of the device initialization.

Also happens to other devices after i deleted awtrix device.

**Comment by steuerlexi** [comment]
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 277a43992373428da5ae6230c80a0cea.aggregator.light_0x001788010c675a36.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 277a43992373428da5ae6230c80a0cea.aggregator.light_0x001788010c675a36.colorControl.state: Conformance "HS": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at ColorControl$State.set [as currentHue] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1113:18)
        at ColorControlServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1311:9)
        at ColorControlServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1303:14)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by steuerlexi** [comment]
Ahh, and this behavior started with the update to Alpha 29. So maybe it has something to do with it.

**Comment by DJBenson** [comment]
Same issue here

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 02ef6e4c0bdf4eb8a78a85f442104c61.aggregator.light_philips_hue_lightstrip_master_bedroom.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 02ef6e4c0bdf4eb8a78a85f442104c61.aggregator.light_philips_hue_lightstrip_master_bedroom.colorControl.state: Conformance "HS": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at ColorControl$State.set [as currentHue] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1113:18)
        at ColorControlServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1311:9)
        at ColorControlServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1303:14)
s6-rc: info: service legacy-services: stopping
```

**Comment by t0bst4r** [comment]
This is a duplicate of #134, lets keep track over there.
