### ISSUE TITLE
3.0.0-alpha.31 issue

### ISSUE THREAD

**Issue by oat1** [t0bst4r/home-assistant-matter-hub#138]
Hello after upgrading to the new version, I have these errors in logs and the addon is not working.

It was working well on previous version 27 or 28 I can't remember  

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 5cd61e4a2f9144a4817d9b2ed319c0fd.aggregator.light_wled.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 5cd61e4a2f9144a4817d9b2ed319c0fd.aggregator.light_wled.colorControl.state.colorTemperatureMireds: Conformance "CT": Matter does not allow you to set this attribute (128)
        at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:305:13)
        at Object.colorTemperatureMireds (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:41:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by pen96** [comment]
same here with led controller

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 2aec7c6b1e14482e94c9eb56ce13ccc6.aggregator.light_bedroom_led_strip.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 2aec7c6b1e14482e94c9eb56ce13ccc6.aggregator.light_bedroom_led_strip.colorControl.state.colorTemperatureMireds: Conformance "CT": Matter does not allow you to set this attribute (128)
        at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:305:13)
        at Object.colorTemperatureMireds (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:41:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23)
s6-rc: info: service legacy-services: stopping
```

**Comment by t0bst4r** [comment]
What kind of lights are these? Do they have color temperature?

**Comment by oat1** [comment]
WLED

**Comment by t0bst4r** [comment]
What features do they have?
Can you post its attributes? (HA -> Developer Tools -> State -> serach for entity id)

**Comment by oat1** [comment]
![image](https://github.com/user-attachments/assets/5664870c-ad03-4ab9-904d-07e0bf3dae3b)

**Comment by t0bst4r** [comment]
okay i found it.
I re-implemented the color control behavior. And made it more clean to differentiate between color control and color temperature. Before every color light also had color temperature - now only those have temperature if they really support it in HA, too.

I'll work on a fix.
In the meantime you can fix it yourself if you have access to the file system (e.g. with the file editor addon)

If yes:
- go to the addon config / data directory
- you will find an "app.json" and one additional json PER bridge
- open the json file of the bridge which includes the problematic entity
- search the file for "colorControl" until you find `root.parts.aggregator.parts.light_your_entity.colorControl`
- i expect it to have the `colorTemperatureMireds` property - if yes: remove it

**Comment by oat1** [comment]
thanks for the help @t0bst4r :)

I have access to the file system but do not see the home-assistant-matter-hub folder there.
I guess I will wait for the new release
