### ISSUE TITLE
Climate entities cause bridge to crash

### ISSUE THREAD

**Issue by DJBenson** [t0bst4r/home-assistant-matter-hub#16]
I'm just moving my setup over from the old bridge to a new one and I'm getting a crash when I add any climate entities. The bridge recovers if I remove the climate entity.

Config:
```
{
  "name": "Main",
  "port": 5540,
  "filter": {
    "include": [
      { "type": "label", "value": "matter" }
    ],
    "exclude": []
  }
}
```

Error:
```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:122:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 771595122ec449f9bfdaf771940bcce1.aggregator.climate_dining_room.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:52:13)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:61:7)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
        at invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:281:26)
        at AsyncConstruction.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:62:9)
        at #createBacking (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:401:26)
        at Behaviors.activate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:236:36)
        at initializeBehaviors (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:113:16)
        at actOffline (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/context/server/OfflineContext.js:29:14)
        at Transaction.act (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/transaction/Tx.js:68:25)
      Caused by: Validating 771595122ec449f9bfdaf771940bcce1.aggregator.climate_dining_room.thermostat.state.controlSequenceOfOperation: Conformance "[HEAT & COOL]": Matter does not allow enum value CoolingAndHeating (ID 4) here (128)
        at Object.<anonymous> (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance-compiler.js:311:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance-compiler.js:371:34
        at Object.controlSequenceOfOperation (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:191:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:38:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:29:23)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:35:5)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ClusterServerBacking.js:60:26)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:56:28)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
```

**Comment by joacim69** [comment]
Tried updating to 3.0.0-alpha.8, but now it seems unstable, can't even get into the Web UI.

**Comment by heatiell** [comment]
Hi,
I've got the exact same issue here. I try to dig in the code to understand what could be the issue, but I didn't success. However, I have a climate with heat HVAC only, after changing its configuration and replace the HVAC heat by heat_cool, it works immediately. So, I suppose the issue is on climate that doesn't support both heat and cool modes

**Comment by heatiell** [comment]
I think, I found the issue. After digging in the matter.js repository, I found the `controlSequenceOfOperation` attribute [here](https://github.com/project-chip/matter.js/blob/c299ab3a88097e23f7531eb928de05e7ec2a5765/packages/types/src/clusters/thermostat.ts#L1425) which is set to `CoolingAndHeating` by default. It seems that if we want to have heating or cooling only, this attribute needs to be set to `HeatingOnly` or `CoolingOnly`

**Comment by t0bst4r** [comment]
Thank you @heatiell 
I’ll take a deeper look

**Comment by heatiell** [comment]
Hi @t0bst4r,
Sorry to bother you again
Thanks for your work on this 🚀 
I just try the v3.0.0-alpha.9 and still have an issue with `HeatingOnly` mode.
Here is the log:
```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:122:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing db9204bb1a98459f9ba152878d0937bf.aggregator.climate_cuisine.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:52:13)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:61:7)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
        at invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:281:26)
        at AsyncConstruction.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:62:9)
        at #createBacking (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:401:26)
        at Behaviors.activate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:236:36)
        at initializeBehaviors (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:113:16)
        at actOffline (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/context/server/OfflineContext.js:29:14)
        at Transaction.act (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/transaction/Tx.js:68:25)
      Caused by: Validating db9204bb1a98459f9ba152878d0937bf.aggregator.climate_cuisine.thermostat.state.occupiedCoolingSetpoint: Conformance "COOL": Matter does not allow you to set this attribute (128)
        at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance-compiler.js:306:13)
        at Object.occupiedCoolingSetpoint (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:191:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:38:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:29:23)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:35:5)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ClusterServerBacking.js:60:26)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:56:28)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
        (see parent frames)
```
It seems that the `occupiedCoolingSetpoint` is set, which is forbidden in this case
