### ISSUE TITLE
UI - Failed to fetch with climate entity

### ISSUE THREAD

**Issue by pbn42** [t0bst4r/home-assistant-matter-hub#161]
Hi,

I'm currently using 3.0.0-alpha.36.

When i try to edit my bridge, i get a "Failed to fetch" red message, and i can't save it.

I'm trying to go from here :
```
{
  "filter": {
    "include": [
      {
        "type": "pattern",
        "value": "switch.prise_chauffage_sdb_haut"
      },
      {
        "type": "pattern",
        "value": "light.prise_cheminee"
      }
    ],
    "exclude": []
  }
}
```

To here :
```
{
  "filter": {
    "include": [
      {
        "type": "pattern",
        "value": "switch.prise_chauffage_sdb_haut"
      },
      {
        "type": "pattern",
        "value": "light.prise_cheminee"
      },
      {
        "type": "pattern",
        "value": "climate.bureau"
      }
    ],
    "exclude": []
  }
}
```

If i try to add a light for example, no trouble.

Here are the logs i get :

```
[ 2024-11-17T13:04:02.166Z ] [ INFO  ] [ matter.js / Node                                   ]: 084f9fec05ca4c61b71e357d9a56789b going offline
[ 2024-11-17T13:04:02.216Z ] [ INFO  ] [ matter.js / ServerNodeStore                        ]: Opened 084f9fec05ca4c61b71e357d9a56789b storage at /config/data/084f9fec05ca4c61b71e357d9a56789b
[ 2024-11-17T13:04:02.217Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 15090542345341473364 and peer node 15090542345341473364 for fabric index 1
[ 2024-11-17T13:04:02.218Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105020275716774273 and peer node 105020275716774273 for fabric index 2
[ 2024-11-17T13:04:02.218Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105022262090359121 and peer node 105022262090359121 for fabric index 2
[ 2024-11-17T13:04:02.219Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 111834613040737521 and peer node 111834613040737521 for fabric index 2
[ 2024-11-17T13:04:02.219Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105827367012191297 and peer node 105827367012191297 for fabric index 2
[ 2024-11-17T13:04:02.220Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 113487183150671697 and peer node 113487183150671697 for fabric index 2
[ 2024-11-17T13:04:02.220Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 110778407003249377 and peer node 110778407003249377 for fabric index 2
[ 2024-11-17T13:04:02.244Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✓index ✓basicInformation ✓accessControl ✓groupKeyManagement ✓generalCommissioning ✓administratorCommissioning ✓operationalCredentials ✓generalDiagnostics ✓commissioning ✓network 💤productDescription 💤sessions 💤controller ✓descriptor
[ 2024-11-17T13:04:02.250Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✓index ✓descriptor
[ 2024-11-17T13:04:02.290Z ] [ INFO  ] [ matter.js / Node                                   ]: 084f9fec05ca4c61b71e357d9a56789b going online
[ 2024-11-17T13:04:02.336Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back initialize<084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau>#66 due to error: Behaviors have errors
[ 2024-11-17T13:04:02.368Z ] [ INFO  ] [ matter.js / Node                                   ]: 084f9fec05ca4c61b71e357d9a56789b is online
[ 2024-11-17T13:04:02.370Z ] [ INFO  ] [ matter.js / AccessControlServer                    ]: initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 18446744060824715265 ], targets: null, fabricIndex: 1 } { privilege: 5, authMode: 2, subjects: [ 18446744060825763885, 18446744060824715265 ], targets: null, fabricIndex: 2 }
[ 2024-11-17T13:04:02.385Z ] [ ERROR ] [ matter.js / Logger                                 ]: Unhandled error detected: Behaviors have errors
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
  at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
  Cause #0: Error initializing 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat
    at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
  Caused by: Validating 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat.state.minSetpointDeadBand: Conformance "AUTO": Matter does not allow you to set this attribute (128)
    at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:305:13)
    at Object.minSetpointDeadBand (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
    at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
    at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:42:7)
    at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23)
file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128
        (causes) => new EndpointBehaviorsError(causes)
                    ^
EndpointBehaviorsError [AggregateError]: Behaviors have errors
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
    at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11 {
  format: [Function: format],
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]],
  [errors]: [
    BehaviorInitializationError: Error initializing 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13) {
      cause: ConformanceError: Validating 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat.state.minSetpointDeadBand: Conformance "AUTO": Matter does not allow you to set this attribute (128)
          at disallowValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:305:13)
          at Object.minSetpointDeadBand (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
          at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
          at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:42:7)
          at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23) {
        code: 128,
        clusterCode: undefined
      }
    }
  ]
}
Node.js v18.20.4
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Home-Assistant-Matter-Hub
 Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
-----------------------------------------------------------
 Add-on version: 3.0.0-alpha.36
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-11-17T13:04:10.190Z ] [ INFO  ] [ Storage                                            ]: Storage location: /config/data
[ 2024-11-17T13:04:10.305Z ] [ INFO  ] [ matter.js / ServerNodeStore                        ]: Opened 084f9fec05ca4c61b71e357d9a56789b storage at /config/data/084f9fec05ca4c61b71e357d9a56789b
[ 2024-11-17T13:04:10.310Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 15090542345341473364 and peer node 15090542345341473364 for fabric index 1
[ 2024-11-17T13:04:10.311Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105020275716774273 and peer node 105020275716774273 for fabric index 2
[ 2024-11-17T13:04:10.312Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105022262090359121 and peer node 105022262090359121 for fabric index 2
[ 2024-11-17T13:04:10.312Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 111834613040737521 and peer node 111834613040737521 for fabric index 2
[ 2024-11-17T13:04:10.313Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 105827367012191297 and peer node 105827367012191297 for fabric index 2
[ 2024-11-17T13:04:10.313Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 113487183150671697 and peer node 113487183150671697 for fabric index 2
[ 2024-11-17T13:04:10.314Z ] [ INFO  ] [ matter.js / SessionManager                         ]: restoring resumption record for node 110778407003249377 and peer node 110778407003249377 for fabric index 2
[ 2024-11-17T13:04:10.437Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✓index ✓basicInformation ✓accessControl ✓groupKeyManagement ✓generalCommissioning ✓administratorCommissioning ✓operationalCredentials ✓generalDiagnostics ✓commissioning ✓network 💤productDescription 💤sessions 💤controller ✓descriptor
[ 2024-11-17T13:04:10.448Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✓index ✓descriptor
[ 2024-11-17T13:04:10.478Z ] [ INFO  ] [ matter.js / Node                                   ]: 084f9fec05ca4c61b71e357d9a56789b going online
[ 2024-11-17T13:04:10.531Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b.aggregator.switch_prise_chauffage_sdb_haut ready endpoint#: 3 type: OnOffPlugInUnit (0x10a) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistant ✓descriptor
[ 2024-11-17T13:04:10.544Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 084f9fec05ca4c61b71e357d9a56789b.aggregator.light_prise_cheminee ready endpoint#: 5 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistant ✓descriptor
[ 2024-11-17T13:04:10.560Z ] [ INFO  ] [ WebApi                                             ]: HTTP server (API & Web App) listening on port 8482
[ 2024-11-17T13:04:10.612Z ] [ INFO  ] [ matter.js / Node                                   ]: 084f9fec05ca4c61b71e357d9a56789b is online
[ 2024-11-17T13:04:10.617Z ] [ INFO  ] [ matter.js / AccessControlServer                    ]: initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 18446744060824715265 ], targets: null, fabricIndex: 1 } { privilege: 5, authMode: 2, subjects: [ 18446744060825763885, 18446744060824715265 ], targets: null, fabricIndex: 2 }
```

Thanks in advance !

**Comment by t0bst4r** [comment]
Your configuration is good. Seems to be a problem with the climate. 
What kind of climate is it? Can you share the attributes of it (HA -> Dev Tools -> States -> search the climate) ?

**Comment by t0bst4r** [comment]
Was this climate included in exactly that bridge before? E.g. before upgrading the addon?

**Comment by pbn42** [comment]
Thanks for your response.

I had this climate in my configuration before alpha 28. But as with alpha28 it kept crashing at start, i removed it from app.json, and i just tried to add it back.

It's a Gree climate. Here are the attributes :

![image](https://github.com/user-attachments/assets/11ba7452-ae20-4a48-aef9-396d7866353c)

**Comment by t0bst4r** [comment]
To me it looks a bit buggy when loading its cached state.

Next to `app.json` there should be another json file with the bridge-id (in your case `084f9fec05ca4c61b71e357d9a56789b.json`)
In there you’ll find some key `root.parts.aggregator.climate_bureau.thermostat` (or `root.parts. 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat` - not sure if the bridge id is part of it) which has a bad state. 
You can safely delete this key from the json.

I consider to just not store the device state, since it only creates problems, and is overridden during initialization anyway.

**Comment by pbn42** [comment]
And concerning the climate integration in HA, if it can help :

- using the gree official integration : https://www.home-assistant.io/integrations/gree/
- also use an HACS extention to manage vertical swing : https://github.com/mullerdavid/hass_GreeExt

Thanks a lot

**Comment by pbn42** [comment]
> To me it looks a bit buggy when loading its cached state.
> 
> Next to `app.json` there should be another json file with the bridge-id (in your case `084f9fec05ca4c61b71e357d9a56789b.json`) In there you’ll find some key `root.parts.aggregator.climate_bureau.thermostat` (or `root.parts. 084f9fec05ca4c61b71e357d9a56789b.aggregator.climate_bureau.thermostat` - not sure if the bridge id is part of it) which has a bad state. You can safely delete this key from the json.
> 
> I consider to just not store the device state, since it only creates problems, and is overridden during initialization anyway.

Thanks a lot, problem solved !

**Comment by pbn42** [comment]
(just to close)
