### ISSUE TITLE
[Bug] Alpha.37 & docker "latest" is broken

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/home-assistant-matter-hub#186]
Due to dependency upgrades an unforeseen error occurs with alpha.37.

```
TypeError: Missing parameter name at 1: https://git.new/pathToRegexpError
    at name (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:73:19)
    at lexer (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:91:27)
    at lexer.next (<anonymous>)
    at Iter.peek (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:106:38)
    at Iter.tryConsume (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:112:28)
    at Iter.text (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:128:30)
    at consume (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:152:29)
    at parse (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:183:20)
    at /usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/path-to-regexp/dist/index.js:294:74
    at Array.map (<anonymous>)
```

**Comment by MichelFR** [comment]
Maybe would also help to redeploy also to docker container registry, there the "latest" is also broken

**Comment by t0bst4r** [comment]
Just removed the broken version, but cannot assign the latest tag via the web ui 🫣
So no latest exists anymore. Ups.

**Comment by MichelFR** [comment]
Fine for now, im setting it to the latest version that did work, thanks for your work!

ghcr.io/t0bst4r/home-assistant-matter-hub:3.0.0-alpha.36

**Comment by t0bst4r** [comment]
fixed
