### ISSUE TITLE
Error when trying to toggle on lights from a matter controller

### ISSUE THREAD

**Issue by jstewart3802** [t0bst4r/home-assistant-matter-hub#208]
Hi, I get the following error when trying to trigger a toggle on lights when the are in the off state in order to turn them on.

```
[ 2024-11-27T21:41:37.282Z ] [ WARN  ] [ Matter / ResourceSet                               ]: Transaction setStateOf<3ebcd2668bdb4307bf929cde24e9d6a6.aggregator.light_kitchen_spotlights>#157e blocked by online#35a4a21@1
[ 2024-11-27T21:41:37.282Z ] [ WARN  ] [ Matter / ResourceSet                               ]: You may need to await transaction.begin() to acquire locks asynchronously
[ 2024-11-27T21:41:37.282Z ] [ ERROR ] [ apply-patch-state                                  ]: Failed to patch the following properties:
{
  "onOff": false
}
[ 2024-11-27T21:41:37.285Z ] [ ERROR ] [ Matter / Transaction                               ]: Error post-commit of 3ebcd2668bdb4307bf929cde24e9d6a6.aggregator.light_kitchen_spotlights.homeAssistantEntity.state: Error in reactor<3ebcd2668bdb4307bf929cde24e9d6a6.aggregator.light_kitchen_spotlights.onOff.update>: Cannot lock 3ebcd2668bdb4307bf929cde24e9d6a6.aggregator.light_kitchen_spotlights.onOff.state synchronously
  at ResourceSet.acquireLocksSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/ResourceSet.js:66:13)
  at Tx.beginSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:198:32)
  at startWrite (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:209:17)
  at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:162:7)
  at OnOff$State.set [as onOff] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
  at Function.assign (<anonymous>)
  at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:926:14)
  at OnOffServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:996:5)
  at #reactWithLocks (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:286:26)
  at #reactWithContext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:262:32)
```

I am using a flic twist through the flic hub that is connected via matter and this seems to work for on, off, brightness and even using toggle from the on state to turn the lights off.

The lights are connected with zigbee to home assistant and exposed through this integration.

If there is any more info I can give, or anything I can try to get this working then please let me know!

Thanks,
James

**Comment by t0bst4r** [comment]
This is caused by a race condition. The command is sent to home assistant and processed faster than matter finishes its transaction. Before the transaction finishes home assistant already reports the updated state.

I had a workaround for that before but it seems that I accidentally removed it during a refactoring.

I’ve prepared a PR for this, but I’ll release it tomorrow after some testing.

**Comment by jstewart3802** [comment]
Thats amazing, thanks for the speed of the reply. I look forward to the fix!

**Comment by t0bst4r** [comment]
Did I read it correct that you connected `home-assistant-matter-hub` with a flic hub using matter?

if yes, I’d love to know more: what is actually working and what doesn’t? Not only related to lights or switches. We don’t have any data for flic hubs. 
additionally I’d like to know if the flic hub couldn’t be directly integrated with home assistant without matter?

**Comment by jstewart3802** [comment]
> Did I read it correct that you connected `home-assistant-matter-hub` with a flic hub using matter?
> 
> if yes, I’d love to know more: what is actually working and what doesn’t? Not only related to lights or switches. We don’t have any data for flic hubs. additionally I’d like to know if the flic hub couldn’t be directly integrated with home assistant without matter?

Yeah! Since the flic hub can now connect matter devices, adding a bridge created in home assistant to the hub you can then control the exposed devices by setting up actions in the flic app. I currently have 3 flic twists connected to the flic hub controlling exposed lights, but am only in the very initial stages of testing it out.

I think there is an integration somewhere made to integrate the flic hub directly into home assistant (maybe flic2hass) but it doesn't support the flic twists as the flic SDK doesn't support them for some reason. Or at least didn't, not sure if that has been updated.

I can answer any other questions if you have them, and can try controlling more devices than lights at some point, but have only tried a couple of lights so far with it.

I'm currently away from home, but once back I'll update the integration at test out the update!

**Comment by wernerhp** [comment]
Oh, boy. flic twist is so bad. I also connect it via Matter Hub to HA. It's the only way I could find that it sort of works, but I get errors when toggling lights on/off. 

```
2025-10-17 20:07:55.070 WARN   ResourceSet          You may need to await transaction.begin() to acquire locks asynchronously
2025-10-17 20:07:55.070 ERROR  Transaction          Error post-commit of 6b2976f112074057983864175da92d4b.aggregator.light_bed_lamp_right.homeAssistantEntity.state: Error in reactor<6b2976f112074057983864175da92d4b.aggregator.light_bed_lamp_right.levelControl.update>: Failed to patch the following properties: {
    "currentLevel": 120.05882352941177,
    "onLevel": 120.05882352941177
  }
    at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1948:13)
    at LevelControlServerBase.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3315:5)
    at #reactWithContext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:272:12)
    at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:202:44)
    at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:110:35)
    at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:20)
    at EventProxy.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:137:12)
    at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:20)
    at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:137:12)
    at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:463:30)
  Caused by: [synchronous-transaction-conflict] Cannot lock 6b2976f112074057983864175da92d4b.aggregator.light_bed_lamp_right.levelControl.state synchronously
    at ResourceSet.acquireLocksSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/transaction/ResourceSet.js:67:13)
    at Tx.beginSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/transaction/Tx.js:152:32)
    at startWrite (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:317:17)
    at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:268:7)
    at Object.set [as currentLevel] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:130:32)
    at Function.assign (<anonymous>)
    at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1946:14)
    at LevelControlServerBase.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3315:5)
    (see parent frames)
```
