### ISSUE TITLE
thermostat: Too many pending tasks in queue ' + key

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#216]
Found alpha 43 matter hub daemon stopped this morning. Saw this in log during the night:

```
[ 2024-11-29T01:20:51.002Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Too many pending tasks in queue climate.thermostat_salon
  at AsyncLock.acquire (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197:15)
  at BridgeDeviceManager.updateEntity (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2436:16)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:48
  at Array.map (<anonymous>)
  at BridgeDeviceManager.updateEntities (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:28)
  at Object.setState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/store.js:19:32)
  at processEvent (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2258:9)
  at conn.subscribeMessage.type [as callback] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2265:40)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/connection.js:23:34
  at Array.forEach (<anonymous>)
/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197
		done(false, new Error('Too many pending tasks in queue ' + key));
		            ^
Error: Too many pending tasks in queue climate.thermostat_salon
    at AsyncLock.acquire (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197:15)
    at BridgeDeviceManager.updateEntity (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2436:16)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:48
    at Array.map (<anonymous>)
    at BridgeDeviceManager.updateEntities (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:28)
    at Object.setState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/store.js:19:32)
    at processEvent (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2258:9)
    at conn.subscribeMessage.type [as callback] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2265:40)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/connection.js:23:34
    at Array.forEach (<anonymous>)
Node.js v18.20.4
```

**Comment by kennylevinsen** [comment]
I believe the default limit for the number of pending `acquire` calls for `async-lock` is 1000, with the most likely scenario being that 1000 state changes happened on that single entity while a service action for the same entity (e.g., "turn thing off") was hanging.

I wonder if there's a previously undiscovered issue on your homeassistant setup causing the action take take indefinite time (or change state at very extreme rates), but possible fixes for our side:

1. Remove the pending limit
2. Implement logic to immediately supersede older states so only the latest state waits. Might be a bit tricker with `async-lock`.

**Comment by KipK** [comment]
I think I now what happened, I saw few days ago  when the matter bridge addon is enabled, sometime when changing setpoint on HASS versatile thermostat , then the thermostat starts to switch temperature hundred times per seconds from set point to 20°. 
Like the bridge send setpoint commands itself.
I have no explanations for that, but this is probably what happened tonight.

**Comment by kennylevinsen** [comment]
Hmm, maybe related to: https://github.com/t0bst4r/home-assistant-matter-hub/issues/170?

**Comment by t0bst4r** [comment]
> Hmm, maybe related to: #170?

Yes I thought about that, too.

> Implement logic to immediately supersede older states so only the latest state waits. Might be a bit tricker with async-lock.

Good idea, but probably not the issue. I‘d expect a queue size of 1000 per entity to be enough 😅

I’d strongly prefer fixing the root cause (infinite state changes).

**Comment by KipK** [comment]
Happened again during the night. This is strange as there was not ativity at this time. 

I've put the matter bridge in debug mode just before , but logs doesn't seems to be more talkative. 

I'm posting it here just in case: https://pastejustit.com/wefltm78pg

**Comment by kennylevinsen** [comment]
I had this happen last night too, added some extra debug logging in case it happens again.

**Comment by kennylevinsen** [comment]
I think I found the deadlock. With a zigbee2mqtt thermostat, it's easily reproducible by restarting homeassistant while the matter hub is running. This will make the thermostat change state to unavailable with no value for temperature, which lands us in `updateEntity`. This state update never returns, leaving us deadlocked for that entity.

During the transaction post-commit for this state update, we end up `targetTemperatureChanged` which does `callAction` for `set_temperature`. As the new state didn't include a temperature, we're trying to set the old one. We try to take the same lock again, deadlocking.

Even if we didn't deadlock, we shouldn't be responding to a state change by asking to have that same state set.

Example of flow with some extra logging:

```
Dec 01 18:25:25 raspberrypi npx[3919]: -> new state 6 for climate.bathroom_radiator (busy: false): {"entity_id":"climate.bathroom_radiator","state":"heat","attributes":{"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"current_temperature":21.5,"temperature":22.5,"hvac_action":"idle","friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M0VRZT0863KSY7C8MN2G0","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:23:17.256Z","last_updated":"2024-12-01T17:24:18.335Z"}
Dec 01 18:25:25 raspberrypi npx[3919]: [ 2024-12-01T17:25:25.562Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#231 locked e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.homeAssistantEntity.state
Dec 01 18:25:25 raspberrypi npx[3919]: [ 2024-12-01T17:25:25.582Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#231 committed and unlocked 1 resource
Dec 01 18:25:25 raspberrypi npx[3919]: [ 2024-12-01T17:25:25.593Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#231 locked e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.homeAssistantEntity.state and e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state
Dec 01 18:25:25 raspberrypi npx[3919]: [ 2024-12-01T17:25:25.615Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#231 committed and unlocked 2 resources
Dec 01 18:25:25 raspberrypi npx[3919]: <- new state 6 for climate.bathroom_radiator
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.081Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.identifyTime via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.083Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.identifyType via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.085Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.clusterRevision via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.086Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.featureMap via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.088Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.attributeList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.089Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.acceptedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.091Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.identify.state.generatedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.093Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.deviceTypeList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.095Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.serverList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.097Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.clientList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.099Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.partsList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.101Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.clusterRevision via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.103Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.featureMap via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.105Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.attributeList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.107Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.acceptedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.109Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.descriptor.state.generatedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.111Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.localTemperature via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.113Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.controlSequenceOfOperation via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.115Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.systemMode via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.117Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.thermostatRunningState via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.119Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.clusterRevision via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.122Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.featureMap via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.124Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.attributeList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.126Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.acceptedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.137Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.generatedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.139Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.absMinHeatSetpointLimit via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.141Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.absMaxHeatSetpointLimit via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.144Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.occupiedHeatingSetpoint via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.146Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.minHeatSetpointLimit via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.148Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state.maxHeatSetpointLimit via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.150Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.nodeLabel via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.152Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.reachable via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.154Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.clusterRevision via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.156Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.featureMap via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.158Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.attributeList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.161Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.acceptedCommandList via online#68c7549@8fbeda35
Dec 01 18:25:52 raspberrypi npx[3919]: [ 2024-12-01T17:25:52.163Z ] [ DEBUG ] [ Matter / Behavior                                  ]: Read e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state.generatedCommandList via online#68c7549@8fbeda35
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 34 for climate.bathroom_radiator (busy: false): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 37 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 41 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 46 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 52 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 59 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 67 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 76 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 86 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 97 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 109 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 122 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 136 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 151 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 167 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 184 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 202 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 222 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: -> new state 243 for climate.bathroom_radiator (busy: true): {"entity_id":"climate.bathroom_radiator","state":"unavailable","attributes":{"restored":true,"hvac_modes":["heat"],"min_temp":5,"max_temp":35,"target_temp_step":0.5,"friendly_name":"Floor heating","supported_features":385},"context":{"id":"01JE1M52D0TM509P9Q30DXFZ28","parent_id":null,"user_id":null},"last_changed":"2024-12-01T17:26:36.192Z","last_updated":"2024-12-01T17:26:36.192Z"}
Dec 01 18:26:36 raspberrypi npx[3919]: [ 2024-12-01T17:26:36.721Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#b55 locked e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.homeAssistantEntity.state
Dec 01 18:26:36 raspberrypi npx[3919]: [ 2024-12-01T17:26:36.745Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#b55 committed and unlocked 1 resource
Dec 01 18:26:36 raspberrypi npx[3919]: [ 2024-12-01T17:26:36.765Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#b55 locked e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.homeAssistantEntity.state and e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.thermostat.state
Dec 01 18:26:36 raspberrypi npx[3919]: [ 2024-12-01T17:26:36.800Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#b55 locked e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator.bridgedDeviceBasicInformation.state
Dec 01 18:26:36 raspberrypi npx[3919]: [ 2024-12-01T17:26:36.908Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction setStateOf<e580364cb1d941ea95890ffef08a2062.aggregator.climate_bathroom_radiator>#b55 committed and unlocked 3 resources
Dec 01 18:26:36 raspberrypi npx[3919]: -> callAction 8 for climate.bathroom_radiator, climate, set_temperature {"temperature":20}
```
