### ISSUE TITLE
Light color change fails with "State has not settled after 5 pre-commit cycles"

### ISSUE THREAD

**Issue by kennylevinsen** [t0bst4r/home-assistant-matter-hub#225]
```
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.703Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: New exchange channel: udp://fd82:78c2:d859:d942:7174:a5aa:7c02:3171:5540 on session secure/10637 protocol: 1 id: 43049 session: secure/10637 peerSessionId: 10637 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.704Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: Message « id: 10637/43049/231416672 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000e2501000324020a1835012400fa24010224020124030118181824ff0b18
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.706Z ] [ DEBUG ] [ Matter / InteractionServer                         ]: Received invoke request from udp://fd82:78c2:d859:d942:7174:a5aa:7c02:3171:5540 on session secure/10637 with 1 commands: ColorTemperatureLight(0xe)/ColorControl(0x300)/moveToColorTemperature(0xa), suppressResponse=false
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.710Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke e580364cb1d941ea95890ffef08a2062.aggregator.light_hallway_lamp.colorControl.moveToColorTemperature online#dcb2360@8fbeda35 colorTemperatureMireds: 250 transitionTime: 2 optionsMask: { executeIfOff: true } optionsOverride: { executeIfOff: true }
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.711Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction online#dcb2360@8fbeda35 locked e580364cb1d941ea95890ffef08a2062.aggregator.light_hallway_lamp.colorControl.state
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.715Z ] [ DEBUG ] [ HomeAssistantActions                               ]: Calling action 'light.turn_on' for target {"entity_id":"light.hallway_lamp"} with data {"color_temp_kelvin":4000}
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.718Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: New exchange channel: udp://fd82:78c2:d859:d942:7174:a5aa:7c02:3171:5540 on session secure/10637 protocol: 1 id: 43050 session: secure/10637 peerSessionId: 10637 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.719Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: Message « id: 10637/43050/231416673 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000e24010624020118350118181824ff0b18
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.721Z ] [ DEBUG ] [ Matter / InteractionServer                         ]: Received invoke request from udp://fd82:78c2:d859:d942:7174:a5aa:7c02:3171:5540 on session secure/10637 with 1 commands: ColorTemperatureLight(0xe)/OnOff(0x6)/on(0x1), suppressResponse=false
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.725Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke e580364cb1d941ea95890ffef08a2062.aggregator.light_hallway_lamp.onOff.on online#dcb2361@8fbeda35 (no payload)
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.726Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction online#dcb2361@8fbeda35 locked e580364cb1d941ea95890ffef08a2062.aggregator.light_hallway_lamp.onOff.state
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.728Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction online#dcb2361@8fbeda35 committed and unlocked 1 resource
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.730Z ] [ DEBUG ] [ Matter / ExchangeManager                           ]: Message » id: 10637/43050/105865407 type: 1/9 acked: 231416673 reqAck: true duplicate: false payload: 1528003601153501370024000e2401062402011835012400001818181824ff0c18
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.736Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: Message « id: 10637/43050/231416674 type: 0/16 acked: 105865407 reqAck: false duplicate: false payload:
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.745Z ] [ ERROR ] [ Matter / Transaction                               ]: State has not settled after 5 pre-commit cycles which likely indicates an infinite loop
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.746Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction online#dcb2360@8fbeda35 rolled back and unlocked 1 resource
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.751Z ] [ WARN  ] [ Matter / InteractionMessenger                      ]: Rolled back due to pre-commit error
Nov 30 14:00:37 raspberrypi npx[65179]:   at errorRollback (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:325:13)
Nov 30 14:00:37 raspberrypi npx[65179]:   at nextCycle (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:333:16)
Nov 30 14:00:37 raspberrypi npx[65179]:   at nextPreCommit (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:349:28)
Nov 30 14:00:37 raspberrypi npx[65179]:   at #executePreCommit (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:376:12)
Nov 30 14:00:37 raspberrypi npx[65179]:   at Tx.commit (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:240:42)
Nov 30 14:00:37 raspberrypi npx[65179]:   at commitTransaction (file:///opt/matterhub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:33:23)
Nov 30 14:00:37 raspberrypi npx[65179]:   at async TransactionalInteractionServer.handleInvokeRequest (file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/interaction/InteractionServer.js:951:20)
Nov 30 14:00:37 raspberrypi npx[65179]:   at async InteractionServerMessenger.handleRequest (file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/interaction/InteractionMessenger.js:138:13)
Nov 30 14:00:37 raspberrypi npx[65179]:   at async ExchangeManager.onMessage (file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:207:9)
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.757Z ] [ DEBUG ] [ Matter / ExchangeManager                           ]: Message » id: 10637/43049/105865408 type: 1/1 acked: 231416672 reqAck: true duplicate: false payload: 1524000124ff0c18
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.762Z ] [ DEBUG ] [ Matter / MessageExchange                           ]: Message « id: 10637/43049/231416675 type: 1/1 acked: 105865408 reqAck: true duplicate: false payload: 1524008024ff0b18
Nov 30 14:00:37 raspberrypi npx[65179]: [ 2024-11-30T13:00:37.764Z ] [ DEBUG ] [ Matter / ExchangeManager                           ]: Message » id: 10637/43049/105865409 type: 0/16 acked: 231416675 reqAck: false duplicate: false payload:
```

**Comment by t0bst4r** [comment]
Somehow i'd expect that to be related with the lock error (#216).
Transaction cannot be cancelled within x seconds (maybe because the lock is taking too long).

Does this happen all the time or just once in a while?

**Comment by Apollon77** [comment]
In fact the error means that within the transaction ore then 5 value updates came in which means something is maybe strange. So, as said before: the way to go is to send out the command in the command handling logic, but report back "changed values because of the command" outside of the command trx context

**Comment by kennylevinsen** [comment]
Okay, so we're calling `moveToColorTemperature`, [which implicitly calls](https://github.com/project-chip/matter.js/blob/d3c8403024dc26404a527ccd0ec019c6e4bea2b4/packages/node/src/behaviors/color-control/ColorControlServer.ts#L978) `this.setColorMode(ColorControl.ColorMode.ColorTemperatureMireds)`. At this time, the current `colorMode` is 0 (`ColorControl.ColorMode.CurrentXAndCurrentY`) seemingly because it is not initialized, causing an attempt at converting from XY to mireds.

This reads `this.x`, [which triggers](https://github.com/project-chip/matter.js/blob/d3c8403024dc26404a527ccd0ec019c6e4bea2b4/packages/node/src/behaviors/color-control/ColorControlServer.ts#L130) the `x` getter. Because `this.currentX` is undefined, the conversion there returns `NaN` and everything goes bad.

I wonder why we don't have old color modes and values stored...
