### ISSUE TITLE
bug: Google Home fails to reconnect after service restart

### ISSUE THREAD

**Issue by kennylevinsen** [t0bst4r/home-assistant-matter-hub#228]
Bridge and devices become and stay offline after service restart. Hint regarding what to look for would be great - can try to lost debug logs, but didn't see anything on first glance.

HomeKit stays connected to the second bridge though.

**Comment by t0bst4r** [comment]
Does it happen everytime you restart the app? But only for Google Home and not Apple Home?

**Comment by kennylevinsen** [comment]
Happened both times my HA server restarted after setting things up. HomeKit comes back up fine, Google home not so.

Will try with a small test server to see, setting up room associations after recreating a bridge for Google Home gets old real quick :|

**Comment by t0bst4r** [comment]
Does it happen when you restart the addon, or only when restarting the whole home assistant system?

**Comment by kennylevinsen** [comment]
I was apparently seeing two different issues and drawing a rushed conclusion:

1. Crash (the 1000 pending lock queue issue) where restart of the service didn't help. Unfortunately the volatile journal was lost to the next one. My suspicion was that something had gone bad in the persisted bridge state, but I cannot reproduce.

2. Power-loss where matter-hub seemed to start too early, failed but stayed alive so no service restart (and I as I had to leave thought it was a repeat of the above):

```
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.659Z ] [ DEBUG ] [ Matter / UdpChannelNode                            ]: Socket created and bound remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.684Z ] [ ERROR ] [ Matter / MdnsService                               ]: No IPv4 addresses on interface: eth0
Nov 30 15:40:17 raspberrypi npx[1128]:   at NodeJsUdpChannel.create (file:///opt/matterhub/node_modules/@matter/nodejs/dist/esm/net/NodeJsUdpChannel.js:72:17)
Nov 30 15:40:17 raspberrypi npx[1128]:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 30 15:40:17 raspberrypi npx[1128]:   at async UdpMulticastServer.create (file:///opt/matterhub/node_modules/@matter/general/dist/esm/net/UdpMulticastServer.js:32:50)
Nov 30 15:40:17 raspberrypi npx[1128]:   at async MdnsServer.create (file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/mdns/MdnsServer.js:32:7)
Nov 30 15:40:17 raspberrypi npx[1128]:   at async MdnsBroadcaster.create (file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/mdns/MdnsBroadcaster.js:62:7)
Nov 30 15:40:17 raspberrypi npx[1128]:   at async file:///opt/matterhub/node_modules/@matter/protocol/dist/esm/mdns/MdnsService.js:35:27
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.852Z ] [ INFO  ] [ Matter / ServerNodeStore                           ]: Opened 08bae7333ea14453b0dcb15f2cbebf41 storage at /home/homeassistant/.home-assistant-matter-hub/08bae7333ea14453b0dcb15f2cbebf41
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.869Z ] [ INFO  ] [ Matter / SessionManager                            ]: restoring resumption record for node 1680777059 and peer node 1680777059 for fabric index 1
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.872Z ] [ INFO  ] [ Matter / SessionManager                            ]: restoring resumption record for node 499721741 and peer node 499721741 for fabric index 2
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.873Z ] [ INFO  ] [ Matter / SessionManager                            ]: restoring resumption record for node 2682755332 and peer node 2682755332 for fabric index 1
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.875Z ] [ INFO  ] [ Matter / SessionManager                            ]: restoring resumption record for node 94168445 and peer node 94168445 for fabric index 1
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.934Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.basicInformation.state
Nov 30 15:40:17 raspberrypi npx[1128]: [ 2024-11-30T14:40:17.995Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.accessControl.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.018Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.groupKeyManagement.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.048Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.generalCommissioning.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.067Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.administratorCommissioning.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.093Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.operationalCredentials.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.136Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.generalDiagnostics.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.197Z ] [ DEBUG ] [ Matter / EventHandler                              ]: Set/Restore last event number: 40
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.199Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 locked 08bae7333ea14453b0dcb15f2cbebf41.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.223Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41>#1 committed and unlocked 8 resources
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.238Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 08bae7333ea14453b0dcb15f2cbebf41 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✓index ✓basicInformation ✓accessControl ✓groupKeyManagement ✓generalCommissioning ✓administratorCommissioning ✓operationalCredentials ✓generalDiagnostics ✓c>
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.243Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction reactor<08bae7333ea14453b0dcb15f2cbebf41.commissioning.#initializeNode>#5 locked 08bae7333ea14453b0dcb15f2cbebf41.commissioning.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.246Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction reactor<08bae7333ea14453b0dcb15f2cbebf41.commissioning.#initializeNode>#5 committed and unlocked 1 resource
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.261Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator>#9 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.264Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction reactor<08bae7333ea14453b0dcb15f2cbebf41.descriptor.#updatePartsList>#a locked 08bae7333ea14453b0dcb15f2cbebf41.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.267Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction reactor<08bae7333ea14453b0dcb15f2cbebf41.descriptor.#updatePartsList>#a committed and unlocked 1 resource
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.269Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator>#9 committed and unlocked 1 resource
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.274Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 08bae7333ea14453b0dcb15f2cbebf41.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✓index ✓descriptor
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.494Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_denon_avr_x1700h>#1c locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_denon_avr_x1700h.identify.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.514Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_living_room>#21 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_living_room.identify.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.527Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights>#26 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights.identify.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.545Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights>#26 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights.groups.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.555Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights>#2b locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights.identify.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.561Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights>#2b locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights.groups.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.573Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_denon_avr_x1700h>#1c locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_denon_avr_x1700h.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.576Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_living_room>#21 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.media_player_living_room.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.579Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights>#26 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights.onOff.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.581Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights>#26 locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_office_lights.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.583Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights>#2b locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights.onOff.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.585Z ] [ DEBUG ] [ Matter / Transaction                               ]: Transaction initialize<08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights>#2b locked 08bae7333ea14453b0dcb15f2cbebf41.aggregator.light_bedroom_lights.descriptor.state
Nov 30 15:40:18 raspberrypi npx[1128]: [ 2024-11-30T14:40:18.587Z ] [ ERROR ] [ Bridge / 08bae7333ea14453b0dcb15f2cbebf41          ]: Failed to start bridge due to error: TypeError: Cannot read properties of undefined (reading 'attributes')
Nov 30 15:40:18 raspberrypi npx[1128]:     at LightDevice (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1310:55)
Nov 30 15:40:18 raspberrypi npx[1128]:     at createDevice (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2166:10)
Nov 30 15:40:18 raspberrypi npx[1128]:     at BridgeDeviceManager.upsertDevice (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2416:26)
Nov 30 15:40:18 raspberrypi npx[1128]:     at file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2405:21
Nov 30 15:40:18 raspberrypi npx[1128]:     at Array.map (<anonymous>)
Nov 30 15:40:18 raspberrypi npx[1128]:     at BridgeDeviceManager.upsertDevices (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2403:16)
Nov 30 15:40:18 raspberrypi npx[1128]:     at async BridgeDeviceManager.loadDevices (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2377:25)
Nov 30 15:40:18 raspberrypi npx[1128]:     at async _BridgeServerNode.start (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2531:7)
Nov 30 15:40:18 raspberrypi npx[1128]:     at async _BridgeService.initialize (file:///opt/matterhub/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2596:7)
```

For that one, it seems that a process exit is missing for fatal issues.

**Comment by t0bst4r** [comment]
Is there any way to detect that home assistant is not yet ready? I don't find the HA websocket api well documented.
Similar to the message that the UI is showing during HA restart?
We could delay everything until it detects HA to be fully running.
