### ISSUE TITLE
ERROR 503: Service unavailable - 3.0.0-alpha.47

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/home-assistant-matter-hub#230]
Unfortunately home assistant seems to have some problems when addons switch from "non-ingress" to using ingress.

I have seen this behavior, too. No worries.
As you can see in the logs, the app is booting.

It seems that the ingress server does not pick up the change immediately. For me it took about 5 minutes until the error message disappeared.
If that doesn't work you could try one of two options:
- re-install the addon. **DO NOT REMOVE THE STORAGE** when uninstalling. When you install it again it will pick up the not-deleted storage and your bridge should be back running and still be paired.
- reboot your Home Assistant instance

**Comment by myevit** [comment]
thank!
whole system reboot did the trick. all working now.

**Comment by tam481** [comment]
Hi @t0bst4r 
With regards to https://github.com/t0bst4r/home-assistant-matter-hub/issues/98#issuecomment-2509064383

I already posted the error in the now closed issue
https://github.com/t0bst4r/home-assistant-matter-hub/issues/98#issuecomment-2508715574

I think I'm confused about how HAMH is supposed to work and interact with Home Assistant with how the "old" Matterbridge works.

I've got both HA and HAMH running on the same host and I'm passing on the parameter `"homeAssistantUrl": "https://hass.mydomain.co.uk/"` in my config.json file but when I start HAMH I get


```
[ 2024-11-30T17:49:05.579Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Unable to connect to home assistant: SyntaxError: Invalid URL: ws://x.x.x.x:yyyy/api/websocket
  at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727:14)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:711:18
  at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:705:23)
file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727
      return new Error(`Unable to connect to home assistant: ${reason}`);
             ^

Error: Unable to connect to home assistant: SyntaxError: Invalid URL: ws://x.x.x.x:yyyy/api/websocket
    at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:727:14)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:711:18
    at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:705:23)

Node.js v20.18.1
```

Here is my config.json

```
{
    "homeAssistantUrl": "https://hass.mydomain.co.uk",
    "homeAssistantAccessToken": "REDACTED",
    "logLevel": "debug"
}
```

**Comment by DJBenson** [comment]
Worked first time for me. Thanks @t0bst4r.

**Comment by aebgit** [comment]
For 1-2 minutes after enabling ingress, i had the 500-error too. Then it just started working by itself.

Thanks for this nice feature!
