### ISSUE TITLE
Can't add to any fabric

### ISSUE THREAD

**Issue by elliana-wt** [t0bst4r/home-assistant-matter-hub#244]
```
2024-12-02T06:15:08.646Z ] [ ERROR ] [ Matter / CaseServer                                ]: An error occurred during the commissioning Fabric cannot be found from destinationId
  at FabricManager.findFabricFromDestinationId (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/fabric/FabricManager.js:184:11)
  at CaseServer.handleSigma1 (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/session/case/CaseServer.js:115:36)
  at async CaseServer.onNewExchange (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/session/case/CaseServer.js:36:7)
  at async SecureChannelProtocol.onNewExchange (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/securechannel/SecureChannelProtocol.js:122:9)
  at async ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:207:9)
```

**Comment by elliana-wt** [comment]
Here's all the logs when I trying to add the lights into Apple Homekit:

```
[ 2024-12-03T08:41:40.846Z ] [ INFO  ] [ Matter / PaseServer                                ]: Received pairing request from udp://192.168.1.224:63949.
[ 2024-12-03T08:41:41.066Z ] [ INFO  ] [ Matter / PaseServer                                ]: Session 28643 created with udp://192.168.1.224:63949.
[ 2024-12-03T08:41:41.073Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/5840283951252374126
[ 2024-12-03T08:41:43.396Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.armFailSafe online#edbbb6f@0 expiryLengthSeconds: 60 breadcrumb: 4
[ 2024-12-03T08:41:43.415Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.setRegulatoryConfig online#edbbb71@0 newRegulatoryConfig: 2 countryCode: CN breadcrumb: 5
[ 2024-12-03T08:41:43.428Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.certificateChainRequest online#edbbb73@0 certificateType: 2
[ 2024-12-03T08:41:43.459Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.certificateChainRequest online#edbbb75@0 certificateType: 1
[ 2024-12-03T08:41:43.469Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.attestationRequest online#edbbb77@0 attestationNonce: e854c7c2b0229ad0ff74b80fad7b130115291f2c6d8fa007c8bfdef59a068cd2
[ 2024-12-03T08:41:43.489Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.armFailSafe online#edbbb79@0 expiryLengthSeconds: 60 breadcrumb: 14
[ 2024-12-03T08:41:45.261Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.csrRequest online#edbbb7c@0 csrNonce: 8346006dc4b0798f4c9f0c715c14adb0f520d7f5ad7d994258fb29458f6cb792
[ 2024-12-03T08:41:45.277Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.addTrustedRootCertificate online#edbbb7e@0 rootCaCertificate: 1530010100240201370326140a7b2f0f2615f5249aeb1826045ba5c82d240500370626140a7b2f0f2615f5249aeb1824070124080130094104ed1a353f8827c5bb24e0eecdfcabe2c64f33a07edc4ee05c9885ee35a2573029a170b1844a7967299e21b1dd759a78e671bed9ab2280b1eb51c9ca894f4861f0370a3501290118240260300414005167b05c45092d4b401e69354be90f82daade4300514005167b05c45092d4b401e69354be90f82daade418300b40a6f7b2efbcdc78043a6190dbc1bfa5c52aef6a2a614b12608a1d9a5ab044ab2d5f312ff8c30d08dc50c71ce02bb8bc0c79e045e37f429f6f05ec14c7d89b10dc18
[ 2024-12-03T08:41:45.297Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.addNoc online#edbbb7f@0 nocValue: 1530010101240201370326140a7b2f0f2615f5249aeb182604c980e12e24050037062615f5249aeb26118c31912c1824070124080130094104dc8b2e11ffc85799fbcc322ed0154e4c84479b709904ce6ee1b623d4d3281d94ae0eca75b43d6e56a7c13d303e59476ca077b9daa7a36895963ca68053430721370a350128011824020136030402040118300414bb34bcc009182a281ecdbb30568253aba413312a300514005167b05c45092d4b401e69354be90f82daade418300b4096646dfa0f1a735d1f83128784444754afcedbe1462d33ac6fa1e48cc585379a653599f3d5473b2da24eeabd30cb99f3583cf0cc71483559b710a6a57e8bc90f18 icacValue:  ipkValue: 3d54459b8fb7d55bcbaca25e323df217 caseAdminSubject: 2867954549 adminVendorId: 4937
[ 2024-12-03T08:41:45.308Z ] [ INFO  ] [ Matter / DeviceCommissioner                        ]: Announce done fabric: 3952747765 fabricIndex: 1
[ 2024-12-03T08:41:45.329Z ] [ INFO  ] [ Matter / Operationa~edentials                      ]: addNoc success, adminVendorId 4937, caseAdminSubject 2867954549
[ 2024-12-03T08:41:45.336Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: ACL updated, updating ACL manager { fabricIndex: 1, privilege: 5, authMode: 2, subjects: [ 2867954549 ], targets: null }
[ 2024-12-03T08:42:42.900Z ] [ INFO  ] [ Matter / CaseServer                                ]: Received pairing request from udp://192.168.1.224:63949
[ 2024-12-03T08:42:42.908Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.armFailSafe online#edbbb82@0 expiryLengthSeconds: 118 breadcrumb: 30
[ 2024-12-03T08:42:42.935Z ] [ INFO  ] [ Matter / CaseServer                                ]: session 28644 created with udp://192.168.1.224:63949 for Fabric 000000002C91318C(index 1) and PeerNode 00000000AAF18375 with CATs 2534932481
[ 2024-12-03T08:42:43.042Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.commissioningComplete online#1174fdd@aaf18375 (no payload)
[ 2024-12-03T08:42:43.045Z ] [ INFO  ] [ Matter / DeviceCommissioner                        ]: All announcements stopped
[ 2024-12-03T08:42:43.046Z ] [ INFO  ] [ Matter / SecureSession                             ]: Register Session secure/28643 to close when exchange is ended.
[ 2024-12-03T08:42:43.049Z ] [ INFO  ] [ Matter / GeneralCom~erHandler                      ]: Commissioning completed on fabric #3952747765 as node #747712908.
[ 2024-12-03T08:42:43.054Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/4092303129017307166
[ 2024-12-03T08:42:43.081Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: Register ACL update to be delayed
[ 2024-12-03T08:42:43.083Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Set remote value for fabric scoped attribute "acl" to []
[ 2024-12-03T08:42:43.085Z ] [ INFO  ] [ Matter / Behavior                                  ]: Write 715c1e87a6894f3a8809f8eb51b60679.accessControl.state.acl via online#1174fdf@aaf18375
[ 2024-12-03T08:42:43.087Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Delay change for attribute "acl" with value []
[ 2024-12-03T08:42:43.089Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: ACL updated, but ACL manager update is delayed 
[ 2024-12-03T08:42:43.093Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Set remote value for fabric scoped attribute "acl" to [{"privilege":5,"authMode":2,"subjects":["18446744063359582209","3951609813"],"targets":null,"fabricIndex":1}]
[ 2024-12-03T08:42:43.095Z ] [ INFO  ] [ Matter / Behavior                                  ]: Write 715c1e87a6894f3a8809f8eb51b60679.accessControl.state.acl via online#1174fdf@aaf18375
[ 2024-12-03T08:42:43.097Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Delay change for attribute "acl" with value [{"privilege":5,"authMode":2,"subjects":["18446744063359582209","3951609813"],"targets":null,"fabricIndex":1}]
[ 2024-12-03T08:42:43.100Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: ACL updated, but ACL manager update is delayed { privilege: 5, authMode: 2, subjects: [ 18446744063359582209, 3951609813 ], targets: null, fabricIndex: 1 }
[ 2024-12-03T08:42:43.104Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Set remote value for fabric scoped attribute "acl" to [{"privilege":5,"authMode":2,"subjects":["18446744063359582209","3951609813"],"targets":null,"fabricIndex":1},{"privilege":3,"authMode":2,"subjects":["18446744062970691586"],"targets":null,"fabricIndex":1}]
[ 2024-12-03T08:42:43.105Z ] [ INFO  ] [ Matter / Behavior                                  ]: Write 715c1e87a6894f3a8809f8eb51b60679.accessControl.state.acl via online#1174fdf@aaf18375
[ 2024-12-03T08:42:43.107Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Delay change for attribute "acl" with value [{"privilege":5,"authMode":2,"subjects":["18446744063359582209","3951609813"],"targets":null,"fabricIndex":1},{"privilege":3,"authMode":2,"subjects":["18446744062970691586"],"targets":null,"fabricIndex":1}]
[ 2024-12-03T08:42:43.112Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: ACL updated, but ACL manager update is delayed { privilege: 5, authMode: 2, subjects: [ 18446744063359582209, 3951609813 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062970691586 ], targets: null, fabricIndex: 1 }
[ 2024-12-03T08:42:43.114Z ] [ INFO  ] [ Matter / AttributeServer                           ]: Trigger delayed change for attribute "acl" with value [{"privilege":5,"authMode":2,"subjects":["18446744063359582209","3951609813"],"targets":null,"fabricIndex":1},{"privilege":3,"authMode":2,"subjects":["18446744062970691586"],"targets":null,"fabricIndex":1}]
[ 2024-12-03T08:42:43.114Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: Committing delayed ACL update
[ 2024-12-03T08:42:43.114Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: Updating ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 18446744063359582209, 3951609813 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062970691586 ], targets: null, fabricIndex: 1 }
[ 2024-12-03T08:42:45.485Z ] [ INFO  ] [ Matter / InteractionServer                         ]: Successfully created subscription 2466570424 for Session 28644. Updates: 0 - 600 => 182 seconds (sendInterval = 91 seconds)
[ 2024-12-03T08:42:45.575Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.generalCommissioning.armFailSafe online#117500e@aaf18375 expiryLengthSeconds: 30 breadcrumb: 0
[ 2024-12-03T08:42:45.591Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.csrRequest online#1175010@aaf18375 csrNonce: 95213b5ce1222f0b3c86ff3f27cade7ea41c8c64f9cc8975190e264198cce7d0 isForUpdateNoc: undefined
[ 2024-12-03T08:42:45.606Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.addTrustedRootCertificate online#1175012@aaf18375 rootCaCertificate: 15300101002402013703271446d4199fb77796f624150118260499de472b2405003706271446d4199fb77796f624150118240701240801300941049855311485ce08eff137a18285da52365bdd51c68c3d15835899311104ebcfa26ed72f6f5e5e2bcf6bf5fe80a404d4fdb6cee75a8ebb3e4a5924147cd3145486370a35012901182402603004141e4d37df71d279f944d2d07030e5a24008a2b3053005141e4d37df71d279f944d2d07030e5a24008a2b30518300b40a079b80d0deabb43db09e9ee2d703962ecbe3f698d8f28a0aa2ce7c684ffa13b6fc9526e60ccd024898da60344183e85fdb47bc73a59d3b5c43a275def8223bd18
[ 2024-12-03T08:42:45.625Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.addNoc online#1175014@aaf18375 nocValue: 15300101012402013703271446d4199fb77796f62415011826040581e12e240500370624150126118a64b2f11824070124080130094104b40dcfd04ee6c7aacc167a9d0d037e8cbb8a3fec20ec06d32f7f0f61bab44a0caf442cf1dc53a7e08c9586951513d6833962d18abe0f72b1348eff85775ae720370a3501280118240201360304020401183004149bfc21cd0bd5729fcbacfe3c6564582620a50e6c3005141e4d37df71d279f944d2d07030e5a24008a2b30518300b40814ce8df69dd7fa5d96cf72c957c7fdb1ae6caf8577c0768c6d95c77315fe7226847e2fd88f81f1ce1b478e9dfa74f120b36d1ac10bbd1dbde5198862b5c21b018 ipkValue: e75dfa43cc206b2acdb3a3bed49d5b7b caseAdminSubject: 8870251377693055671 adminVendorId: 4996 icacValue: undefined
[ 2024-12-03T08:42:45.635Z ] [ INFO  ] [ Matter / DeviceCommissioner                        ]: Announce done fabric: 1 fabricIndex: 2
[ 2024-12-03T08:42:45.636Z ] [ INFO  ] [ Matter / DeviceCommissioner                        ]: Announce done fabric: 1 fabricIndex: 2
[ 2024-12-03T08:42:45.637Z ] [ INFO  ] [ Matter / Operationa~edentials                      ]: addNoc success, adminVendorId 4996, caseAdminSubject 8870251377693055671
[ 2024-12-03T08:42:45.687Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: ACL updated, updating ACL manager { privilege: 5, authMode: 2, subjects: [ 18446744063359582209, 3951609813 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062970691586 ], targets: null, fabricIndex: 1 } { fabricIndex: 2, privilege: 5, authMode: 2, subjects: [ 8870251377693055671 ], targets: null }
[ 2024-12-03T08:43:15.578Z ] [ INFO  ] [ Matter / FailsafeContext                           ]: Failsafe timer expired, Reset fabric builder.
[ 2024-12-03T08:43:43.148Z ] [ INFO  ] [ Matter / CaseServer                                ]: Received pairing request from udp://192.168.1.224:63949
[ 2024-12-03T08:43:43.154Z ] [ ERROR ] [ Matter / CaseServer                                ]: An error occurred during the commissioning Fabric cannot be found from destinationId
  at FabricManager.findFabricFromDestinationId (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/fabric/FabricManager.js:184:11)
  at CaseServer.handleSigma1 (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/session/case/CaseServer.js:115:36)
  at async CaseServer.onNewExchange (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/session/case/CaseServer.js:36:7)
  at async SecureChannelProtocol.onNewExchange (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/securechannel/SecureChannelProtocol.js:122:9)
  at async ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:207:9)
[ 2024-12-03T08:43:43.163Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/10740518866817981521
[ 2024-12-03T08:43:43.392Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke 715c1e87a6894f3a8809f8eb51b60679.operationalCredentials.removeFabric online#1175051@aaf18375 fabricIndex: 1
[ 2024-12-03T08:43:43.430Z ] [ INFO  ] [ Matter / SecureSession                             ]: Register Session secure/28644 to close when exchange is ended.
[ 2024-12-03T08:43:43.462Z ] [ INFO  ] [ Matter / SecureSession                             ]: End CASE session secure/28644
[ 2024-12-03T08:43:43.495Z ] [ INFO  ] [ Matter / Node                                      ]: 715c1e87a6894f3a8809f8eb51b60679 going offline
[ 2024-12-03T08:43:43.700Z ] [ INFO  ] [ Matter / SecureSession                             ]: End PASE session secure/28643
[ 2024-12-03T08:43:43.701Z ] [ INFO  ] [ Matter / Node                                      ]: 715c1e87a6894f3a8809f8eb51b60679 is offline
[ 2024-12-03T08:43:43.701Z ] [ INFO  ] [ Matter / Node                                      ]: 715c1e87a6894f3a8809f8eb51b60679 resetting to factory defaults
[ 2024-12-03T08:43:43.733Z ] [ INFO  ] [ Matter / ServerNodeStore                           ]: Opened 715c1e87a6894f3a8809f8eb51b60679 storage at /config/data/715c1e87a6894f3a8809f8eb51b60679
[ 2024-12-03T08:43:43.784Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✓index ✓basicInformation ✓accessControl ✓groupKeyManagement ✓generalCommissioning ✓administratorCommissioning ✓operationalCredentials ✓generalDiagnostics ✓commissioning ✓network 💤productDescription 💤sessions 💤controller ✓descriptor
[ 2024-12-03T08:43:43.791Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✓index ✓descriptor
[ 2024-12-03T08:43:44.803Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_topwit_rz01_066f_light ready endpoint#: 6 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.807Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_zhimi_ma2_be4d_indicator_light ready endpoint#: 7 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.809Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_topwit_rz01_eeac_light ready endpoint#: 8 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.814Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_3b6c_switch_2 ready endpoint#: 11 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.818Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_3b6c_switch_1 ready endpoint#: 12 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.821Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_f1e1_switch_1 ready endpoint#: 13 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.824Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_aqara_panel_6420_switch1 ready endpoint#: 14 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.826Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_3efa_switch_2 ready endpoint#: 15 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.831Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_3efa_switch_3 ready endpoint#: 16 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.832Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_3efa_switch_1 ready endpoint#: 17 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.832Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_magic_switch_s1e_62a4_switch_2 ready endpoint#: 18 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.834Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_switch2 ready endpoint#: 19 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.835Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_xiaomi_xw002_4c2f_ambient_light ready endpoint#: 20 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.836Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_bias_light ready endpoint#: 24 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.838Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_nanoleaf_a19_4e7v ready endpoint#: 2 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.839Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_nanoleaf_a19_0lr1 ready endpoint#: 3 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.839Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_livingroom_standard_lamp ready endpoint#: 4 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.841Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_studio_desktop_lamp ready endpoint#: 5 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.842Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_closet_light_strip ready endpoint#: 10 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.845Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_underdesk_light_strip ready endpoint#: 21 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.846Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_screenbar ready endpoint#: 22 type: ColorTemperatureLight (0x10c) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.847Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_screenbar_background_light ready endpoint#: 23 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.849Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_aqara_led_strip_t1 ready endpoint#: 25 type: ExtendedColorLight (0x10d) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.858Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 715c1e87a6894f3a8809f8eb51b60679.aggregator.light_philips_bulb_198e_light ready endpoint#: 9 type: ColorTemperatureLight (0x10c) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor
[ 2024-12-03T08:43:44.863Z ] [ INFO  ] [ Matter / Node                                      ]: 715c1e87a6894f3a8809f8eb51b60679 going online
[ 2024-12-03T08:43:44.920Z ] [ INFO  ] [ Matter / Node                                      ]: 715c1e87a6894f3a8809f8eb51b60679 is online
[ 2024-12-03T08:43:44.924Z ] [ INFO  ] [ Matter / AccessControlServer                       ]: initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 18446744063359582209, 3951609813 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062970691586 ], targets: null, fabricIndex: 1 } { privilege: 5, authMode: 2, subjects: [ 8870251377693055671 ], targets: null, fabricIndex: 2 }
```

**Comment by Apollon77** [comment]
In this case it seems that the mobile device or hub is not connecting the bridge to confirm commissioning for the second fabric. So please check if maybe the hub is network wise separated or such

**Comment by MarkusAtCoduct** [comment]
I had the same issue, in my case it was fixed by adding a label to all of the entities I wanted to add and using that label to limit what is added to the bridge rather than just adding all of the entities in my HA instance.

**Comment by t0bst4r** [comment]
> I had the same issue, in my case it was fixed by adding a label to all of the entities I wanted to add and using that label to limit what is added to the bridge rather than just adding all of the entities in my HA instance.

That’s a good hint. How many entities are included in your bridge?
I’ve seen Alexa rejecting pairing processes for many devices.

**Comment by MarkusAtCoduct** [comment]
@t0bst4r For this particular setup it was 132 entities

**Comment by t0bst4r** [comment]
Can you try to only include some entities instead of all those.
I've seen people complaining that Alexa rejects the bridge if it has more than 70-80 devices.

**Comment by MarkusAtCoduct** [comment]
As said, for me it works now that I have limited the entities I actually want to control using alexa (the ones that I could not otherwise which in this case are Ikea smart home things). I'm bot sure I understand your request, do you want me to test at which point alexa refuses the connection ? If so I will gladly run some tests and provide you with my results :)

**Comment by Apollon77** [comment]
Please try again with newest versions of the bridge and reopen with a new log if the issue still exists
