### ISSUE TITLE
3.0.0-alpha.50: Alexa color change - Device not reachable

### ISSUE THREAD

**Issue by floriro** [t0bst4r/home-assistant-matter-hub#252]
When you change the color with Alexa, the color changes but you get a device not reachable message. #210 might be releated, for me with Alexa the problem isn't fixed with the version from today and it happens on every color change. Dim and On/Off works fine.

`[ 2024-12-03T19:10:35.184Z ] [ INFO  ] [ Matter / Behavior                                  ]: Invoke ca87cfffd0054b7095640f71c1559289.aggregator.light_beistelltisch_leuchte.colorControl.moveToHueAndSaturation online#9f432f@3ce020e07742531 hue: 27 saturation: 254 transitionTime: 0 optionsMask: { executeIfOff: false } optionsOverride: { executeIfOff: false }

[ 2024-12-03T19:10:35.188Z ] [ ERROR ] [ Matter / Transaction                               ]: State has not settled after 5 pre-commit cycles which likely indicates an infinite loop

[ 2024-12-03T19:10:35.191Z ] [ WARN  ] [ Matter / InteractionMessenger                      ]: Rolled back due to pre-commit error
  at errorRollback (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:325:13)
  at nextCycle (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:333:16)
  at nextPreCommit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:349:28)
  at #executePreCommit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:376:12)
  at Tx.commit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:240:42)
  at commitTransaction (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:33:23)
  at async TransactionalInteractionServer.handleInvokeRequest (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/interaction/InteractionServer.js:951:20)
  at async InteractionServerMessenger.handleRequest (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/interaction/InteractionMessenger.js:138:13)
  at async ExchangeManager.onMessage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/protocol/ExchangeManager.js:207:9)`

**Comment by myevit** [comment]
In my case alfa50 failed to start at all

**Comment by t0bst4r** [comment]
@myevit 

> In my case alfa50 failed to start at all

can you show the error logs for this? i dont expect the errors to be related.

**Comment by t0bst4r** [comment]
@floriro please upgrade to `alpha.51` and verify if this still happens.

**Comment by floriro** [comment]
Works like a charm, thanks

**Comment by myevit** [comment]
> @myevit
> 
> > In my case alfa50 failed to start at all
> 
> can you show the error logs for this? i dont expect the errors to be related.

https://github.com/t0bst4r/home-assistant-matter-hub/issues/265
