### ISSUE TITLE
[Bug]: Rollershutter -1 not working

### ISSUE THREAD

**Issue by DJFlaxi** [t0bst4r/home-assistant-matter-hub#291]
### Version

3.0.0-alpha.54

### Matter Controller

Alexa

### Steps to reproduce

Hallo,
leider ist mein englisch sehr schlecht, daher schreibe ich in deutsch und hoffe, dass mir trotzdem geholfen werden kann.

Ich habe drei elektrische Rolladen, die leider nicht den Status anzeigen zu wieviel Prozent diese geöffnet bzw. geschlossen sind. Hier wird immer nur "-1" angezeigt.

Wenn ich so einen Rolladen einbinde, startet der HUB nicht und im Protokoll wird dies als Fehler hinterlegt.

Ich hoffe, dass man das noch beheben kann.

Vielen Dank vorab!
Marc

### State and attributes

cover.wz_rollo_rechts

current_position: -1
device_class: shutter
friendly_name: Rollo rechts
supported_features: 11

### Relevant log output

```shell
[ 2024-12-12T09:12:15.372Z ] [ ERROR ] [ Bridge / fd1d3039b9f941409b051f0d04ae7490          ]: Failed to start bridge due to error: Behaviors have errors
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
  at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  Cause #0: Error initializing fd1d3039b9f941409b051f0d04ae7490.aggregator.cover_wz_rollo_rechts.windowCovering
    at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  Caused by: Validating fd1d3039b9f941409b051f0d04ae7490.aggregator.cover_wz_rollo_rechts.windowCovering.state: Constraint "0 to 10000": Value 10100 is not within bounds defined by constraint (135)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/constraint.js:35:17
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:155:25
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:84:24
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:15:22
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
    at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:172:7)
    at WindowCovering$State.set [as currentPositionLiftPercent100ths] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
    at Function.assign (<anonymous>)
    at applyPatchState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1040:14)
    at WindowCoveringServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2060:5)
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by Apollon77** [comment]
Wo kommt denn dann diese -1 her? Aus der Integration die das in HA einbindet?

**Comment by DJFlaxi** [comment]
Ja, genau. Durch die Shelly-Integration.

**Comment by t0bst4r** [comment]
Interessant, dass aus `-1` die Zahl `10100` entsteht - also 101%.
Muss ich mal prüfen warum…

@DJFlaxi 
Kannst du mal bitte die `supported_features` deiner Cover überprüfen:
In HA -> Entwicklertools -> States -> nach dem Cover suchen

Darüber könnten wir erkennen, ob "Position aware" unterstützt sind oder nicht. Wir müssen nur sicher gehen, dass die Integration die Features auch sauber setzt.

**Comment by DJFlaxi** [comment]
Alles was dort angezeigt wird ist das:

current_position: -1
device_class: shutter
friendly_name: Rollo rechts
supported_features: 11

**Comment by t0bst4r** [comment]
Cover Features:
```
    OPEN = 1
    CLOSE = 2
    SET_POSITION = 4
    STOP = 8
    OPEN_TILT = 16
    CLOSE_TILT = 32
    STOP_TILT = 64
    SET_TILT_POSITION = 128
```

In deinem Fall unterstützt das Cover also die Features: open, close und stop.
Die "current position" sollte also nicht verwendet werden. Schaue ich mir an, lässt sich bestimmt fixen.

**Comment by DJFlaxi** [comment]
Top!
Danke schon mal 👍
