### ISSUE TITLE
[Bug]: Matter Hub immediately stop after start

### ISSUE THREAD

**Issue by SebbeDO** [t0bst4r/home-assistant-matter-hub#301]
### Version

3.0.0-alpha.54

### Matter Controller

None so far, not starting

### Steps to reproduce

Just wanted to start Matter Hub on Home Assistant to create first bridge to Alexa

### Relevant log output

```shell
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Home-Assistant-Matter-Hub
 Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
-----------------------------------------------------------
 Add-on version: 3.0.0-alpha.54
 You are running the latest version of this add-on.
 System: Home Assistant OS 14.0  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.12.3
 Home Assistant Supervisor: 2024.11.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/docker-entrypoint.sh: line 11:   175 Killed                  home-assistant-matter-hub start --log-level=$(bashio::config 'app_log_level') --disable-log-colors=$(bashio::config 'disable_log_colors') --mdns-network-interface="$(bashio::config 'mdns_network_interface')" --storage-location=/config/data --web-port=$(bashio::addon.ingress_port) --home-assistant-url='http://supervisor/core' --home-assistant-access-token="$SUPERVISOR_TOKEN" --http-ip-whitelist="172.30.32.2"
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by SebbeDO** [comment]
After letting it go for a while. It´s multiple times starting and stopping and finally giving this info back: "Failed to get 491eb00d_hamh logs, Error in input stream"

**Comment by t0bst4r** [comment]
The "failed to get logs" error is a bug in Home Assistant. You can still download the logs from the HA ui with the icon in the top right corner.

Is it possible to get some more information? CPU and memory usage? Supervisor logs?

**Comment by levanLuongnt** [comment]
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
home-assistant-matter-hub start
start the application
Options:
  --help                         Show help  [boolean]
  --config                       Provide the path to a configuration JSON file, which can include all the other command options. You can use kebabcase ("log-level") or camelcase ("logLevel").
  --log-level  [string] [choices: "silly", "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors  [boolean] [default: false]
  --storage-location             Path to a directory where the application should store its data. Defaults to $HOME/.home-assistant-matter-hub  [string]
  --http-port, --web-port        Port used by the web application. 'http-port' is recommended, 'web-port' is deprecated and will be removed in the future.  [number] [default: 8482]
  --http-ip-whitelist            Only allow the specified IPv4, IPv6 or CIDR. You can specify this option multiple times. When configured via ENV variables, you can only specify ONE value. Defaults to allow every IP address.  [array]
  --mdns-network-interface       Limit mDNS to this network interface  [string]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL  [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assistant Instance  [string] [required]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/storage/StringifyTools.js:40:15)
    at CustomStorage.fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/storage/StorageBackendJsonFile.js:84:12)
    at CustomStorage.parser.fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:686:24)
    at CustomStorage.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/nodejs/dist/esm/storage/StorageBackendJsonFile.js:32:25)
    at async StorageService.open (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/storage/StorageService.js:31:5)
    at async ServerNodeStore.initializeStorage (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/node/storage/ServerNodeStore.js:56:28)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by t0bst4r** [comment]
@levanLuongnt 
Do you have access to the file system (e.g. via FileBrowser addon) ?
Can you please check the content of `/addon_configs/491eb00d_hamh/data/app.json` and other files in the same directory?
All of them should be valid JSON files.

**Comment by schraube05** [comment]
same log output for me like SebbeDO. Im also using the raspberrypi3-64.
I dont have a FileBrowser addon, but i checked via terminal in the /data folder. "ls" command dont show me any files

**Comment by Apollon77** [comment]
is this issue still happening? Did anyone that had it checked for free ram on the host and such? Expect the hub to use minimum 100MB RAM or such
