### ISSUE TITLE
[Bug]: Addon Stops after starting and tryint to create a Bridge

### ISSUE THREAD

**Issue by ashwarsadh** [t0bst4r/home-assistant-matter-hub#307]
### Version

 3.0.0-alpha.54

### Matter Controller

NA

### Steps to reproduce

I installed on Home Assistant Latest 12.3 Core and 14.0 OS
After addon is started it stops working in a while.
I fi open UI and try to create a bridge, either with domain light included or empty, it never saves the bridge as it has already stopeed by then.
I also tried in safe mode, but same issue.
I have attached addon Logs, Supervisor Logs to review.
I see this line in supervisor logs
 Cannot proxy websocket message of unsupported type: 257
 
[supervisor_2024-12-14T20-21-56.452Z.log](https://github.com/user-attachments/files/18137608/supervisor_2024-12-14T20-21-56.452Z.log)
[Addon Log 491eb00d_hamh_2024-12-14T20-20-59.952Z.log](https://github.com/user-attachments/files/18137609/Addon.Log.491eb00d_hamh_2024-12-14T20-20-59.952Z.log)
 

### Relevant log output

```shell
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:135
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:50:39 (2 occurrences)
Last logged: 01:50:46

Failed to to call /addons/491eb00d_hamh/stats - Container addon_491eb00d_hamh is not running


2024-12-15 01:44:14.555 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-15 01:44:50.093 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
2024-12-15 01:44:50.199 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
2024-12-15 01:44:50.203 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for 491eb00d_hamh closed
2024-12-15 01:44:59.077 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:65385 ssl:default [Connect call failed ('172.30.32.1', 65385)]
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by ashwarsadh** [comment]
Here are Debug level logs of addon attached.
[debug log 491eb00d_hamh_2024-12-14T20-37-19.773Z.log](https://github.com/user-attachments/files/18137652/debug.log.491eb00d_hamh_2024-12-14T20-37-19.773Z.log)



here are some more relvent log in supervisor logs:

2024-12-15 02:04:39.152 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 491eb00d/aarch64-addon-hamh with version 3.0.0-alpha.54
2024-12-15 02:04:50.754 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:65385 ssl:default [Connect call failed ('172.30.32.1', 65385)]
2024-12-15 02:04:53.703 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:65385 ssl:default [Connect call failed ('172.30.32.1', 65385)]
2024-12-15 02:04:54.046 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-15 02:04:54.135 INFO (MainThread) [supervisor.api.proxy] WebSocket access from 491eb00d_hamh
2024-12-15 02:04:54.163 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-15 02:05:52.812 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
2024-12-15 02:05:52.130 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
2024-12-15 02:05:52.349 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for 491eb00d_hamh closed
2024-12-15 02:07:35.274 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_491eb00d_hamh application
2024-12-15 02:07:37.728 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 491eb00d/aarch64-addon-hamh with version 3.0.0-alpha.54
2024-12-15 02:07:53.280 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-15 02:07:53.570 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 199, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 215, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 234, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 298, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/proxy.py", line 217, in websocket
    response = await server.receive_json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_ws.py", line 573, in receive_json
    data = await self.receive_str(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_ws.py", line 557, in receive_str
    raise TypeError(
TypeError: Received message 257:None is not WSMsgType.TEXT
2024-12-15 02:08:09.098 ERROR (SyncWorker_3) [supervisor.docker.manager] Container addon_491eb00d_hamh is not running
2024-12-15 02:08:13.699 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_491eb00d_hamh application

**Comment by t0bst4r** [comment]
Can you somehow find out the used memory/cpu during while starting the addon?

You have quite a lot of entities included in your bridge. Can you try starting with a small bridge with just a few devices?

**Comment by ashwarsadh** [comment]
it uses around 12% memory and 1% cpu while starting
I am using Raspberry Pi 4 1 gb ram, but I had htop running on terminal, it had used upto 700mb ram.
Debug logs of crash while on Safe mode and normal mode are attached.
I have created smaller bridge of only 16 devices as i have included only fan domain.
I have also removed unneccsary addons and integrations.
I was able to create bridge now and scan it and add on google home.
But it again got killed.
maybe it is consuming too much memory at some instances.
[debug 491eb00d_hamh_2024-12-15T18-00-53.169Z.log](https://github.com/user-attachments/files/18141589/debug.491eb00d_hamh_2024-12-15T18-00-53.169Z.log)
[debug491eb00d_hamh_2024-12-15T17-43-21.437Z.log](https://github.com/user-attachments/files/18141590/debug491eb00d_hamh_2024-12-15T17-43-21.437Z.log)
