### ISSUE TITLE
[Bug]: Required dependency EndpointInitializer is not available

### ISSUE THREAD

**Issue by Aryankids** [t0bst4r/home-assistant-matter-hub#359]
### Version

Ver 3.0.0, Alpha 58

### Matter Controller

Google Home

### Steps to reproduce

Created two entities in HA. Labelled them and been picked up by the bridge accordingly.
Tried to pair them with GoogleHome via GoogleHome App. 
Went through the process but it hit the brick wall of  EndpointInitializer is not available

### Relevant log output

```shell
[ 2024-12-29T00:43:46.371Z ] [ INFO  ] [ Matter / CaseServer                                ]: Received pairing request from udp://fe80::3cfe:b9ff:fe98:9e8f%enp6s18:41131
[ 2024-12-29T00:43:46.575Z ] [ INFO  ] [ Matter / CaseServer                                ]: session 8594 created with udp://fe80::3cfe:b9ff:fe98:9e8f%enp6s18:41131 for Fabric 000000003273DC0E(index 2) and PeerNode 00000000B868E422 with CATs 65537
[ 2024-12-29T00:43:46.680Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/6379129094936228729
[ 2024-12-29T00:43:47.634Z ] [ ERROR ] [ Matter / Transaction                               ]: Rolling back online#f7e5eba@b868e422 due to error: Required dependency EndpointInitializer is not available
[ 2024-12-29T00:43:47.636Z ] [ ERROR ] [ Matter / InteractionServer                         ]: Error while reading attribute from udp://fe80::3cfe:b9ff:fe98:9e8f%enp6s18:41131 on session secure/8594 to ExtendedColorLight(0x2b4)/Descriptor(0x1d)/deviceTypeList(0x0): Required dependency EndpointInitializer is not available
  at Environment.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/environment/Environment.js:46:11)
  at #createBacking (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:411:40)
  at Behaviors.activate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:242:36)
  at Behaviors.createMaybeAsync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:215:10)
  at Behaviors.createSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:184:27)
  at ExtendedColorLightAgent.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/Agent.js:55:43)
  at behaviorFor (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ClusterServerBacking.js:325:16)
  at FixedAttributeServer.getter (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ClusterServerBacking.js:152:23)
  at FixedAttributeServer.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/cluster/server/AttributeServer.js:175:17)
  at FixedAttributeServer.getWithVersion (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/cluster/server/AttributeServer.js:185:60)
[ 2024-12-29T00:43:47.636Z ] [ WARN  ] [ Matter / InteractionMessenger                      ]: Required dependency EndpointInitializer is not available
  at Environment.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/environment/Environment.js:46:11)
  at #createBacking (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:411:40)
  at Behaviors.activate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:242:36)
  at Behaviors.createMaybeAsync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:215:10)
  at Behaviors.createSync (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:184:27)
  at ExtendedColorLightAgent.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/Agent.js:55:43)
  at behaviorFor (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ClusterServerBacking.js:325:16)
  at FixedAttributeServer.getter (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ClusterServerBacking.js:152:23)
  at FixedAttributeServer.get (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/cluster/server/AttributeServer.js:175:17)
  at FixedAttributeServer.getWithVersion (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/protocol/dist/esm/cluster/server/AttributeServer.js:185:60)
[ 2024-12-29T00:45:43.676Z ] [ INFO  ] [ Matter / FailsafeContext                           ]: Failsafe timer expired, Reset fabric builder.
[ 2024-12-29T00:45:43.708Z ] [ INFO  ] [ Matter / SecureSession                             ]: End CASE session secure/8594
[ 2024-12-29T00:45:43.735Z ] [ INFO  ] [ Matter / SecureSession                             ]: Register Session secure/8593 to close when exchange is ended.
[ 2024-12-29T00:45:43.798Z ] [ INFO  ] [ Matter / UdpMulticastServer                        ]: lo: send ENETUNREACH ff02::fb:5353
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by Apollon77** [comment]
I think a more details debug log would help a lot, ideally from starting the bridge up to this error

**Comment by Aryankids** [comment]
I restarted everything and against all odds, it went through with no issue. No software/dependency etc installed 
Bug cannot be reproduced hence going to close it. 
Many thanks.
