### ISSUE TITLE
[Bug] Climate: Behaviors have errors

### ISSUE THREAD

**Issue by phxZ31** [t0bst4r/home-assistant-matter-hub#47]
My first attempt to install was alpha 11 and now I'm on alpha 12 but neither build actually successfully starts. To be clear, I can't get to the UI even because the add-on simply immediately exits. Here's the log output, hopefully it provides some insight that you can use to help me get it to at least start. Thanks!

```
>s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
>s6-rc: info: service base-addon-banner: starting
>
>
 >Add-on: Home-Assistant-Matter-Hub
 Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or >Google Home.
>
> Add-on version: 3.0.0-alpha.12
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-11-01T04:55:06.711Z ] [ INFO  ] [ Storage                                  ]: Storage location: /config/data
[ 2024-11-01T04:55:07.010Z ] [ INFO  ] [ matter.js / ServerStore                  ]: Opened 8806d8e6953e4104a68c45e236ce73f5 storage at /config/data/8806d8e6953e4104a68c45e236ce73f5
[ 2024-11-01T04:55:08.283Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions ✔descriptor
[ 2024-11-01T04:55:08.312Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✔index ✔descriptor
[ 2024-11-01T04:55:08.331Z ] [ INFO  ] [ matter.js / Node                         ]: 8806d8e6953e4104a68c45e236ce73f5 going online
[ 2024-11-01T04:55:08.673Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.binary_sensor_rpi_power_status ready endpoint#: 2 type: ContactSensor (0x15) behaviors: ✔identify ✔booleanState ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:08.772Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.sensor_econet_etwh_lower_tank_temperature ready endpoint#: 3 type: TemperatureSensor (0x302) behaviors: ✔temperatureMeasurement ✔identify ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:08.819Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.sensor_econet_etwh_upper_tank_temperature ready endpoint#: 4 type: TemperatureSensor (0x302) behaviors: ✔temperatureMeasurement ✔identify ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:08.982Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_beep_on_alarm ready endpoint#: 5 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:09.027Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_screen_adjustment_lock ready endpoint#: 6 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:09.079Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_screen_unit_in_c ready endpoint#: 7 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-01T04:55:09.449Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back initialize<8806d8e6953e4104a68c45e236ce73f5.aggregator.climate_econet_etwh_water_heater>#99 due to error: Behaviors have errors
>home-assistant-matter-hub start
>
>start the application
>
>Options:
  --help                         Show help                             [boolean]
  --log-level
          [string] [choices: "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --mdns-network-interface       Limit MDNS to this network interface   [string]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] 
>[required]
>
>Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:122:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 8806d8e6953e4104a68c45e236ce73f5.aggregator.climate_econet_etwh_water_heater.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:52:13)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:61:7)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
        at invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:281:26)
        at AsyncConstruction.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:62:9)
        at #createBacking (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:401:26)
        at Behaviors.activate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:236:36)
        at initializeBehaviors (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:113:16)
        at actOffline (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/context/server/OfflineContext.js:29:14)
        at Transaction.act (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/transaction/Tx.js:68:25)
      Caused by: Validating 8806d8e6953e4104a68c45e236ce73f5.aggregator.climate_econet_etwh_water_heater.thermostat.state.controlSequenceOfOperation: Conformance "[HEAT & COOL]": Matter does not allow enum value CoolingAndHeating (ID 4) here (128)
        at Object.<anonymous> (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance-compiler.js:311:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance-compiler.js:371:34
        at Object.controlSequenceOfOperation (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:13:15)
        at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:191:23)
        at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:38:7)
        at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:29:23)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:35:5)
        at ClusterServerBacking.invokeInitializer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ClusterServerBacking.js:60:26)
        at [construct] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:56:28)
        at initializeDeferred (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:61:73)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by t0bst4r** [comment]
This is caused by a climate called `climate.econet_etwh_water_heater`.

Can you please add some details what kind of climate it is? Heat & cool or only one of them?
Maybe you can share a screenshot of its attributes and state (HA -> Developer Settings -> Attributes -> search entity id)

**Comment by phxZ31** [comment]
climate.econet_etwh_water_heater_heater is created by an ESPHome integration (esphome-econet) for my Rheem electric water heater. I think they set it up as a climate device in HA to be able to take advantage of the default climate control card in dashboards. 

Is this screenshot the info you needed?
![Screenshot (116)](https://github.com/user-attachments/assets/8153b7f2-603e-4979-b8a6-911c1e3dbe84)

**Comment by t0bst4r** [comment]
okay. i see. i have implemented cooling and heating, but no auto. And your climate is falling through my if-statements to a "default implementation" which is not able to do anything. and then this fallthrough has a bug 😀

**Comment by t0bst4r** [comment]
Yes, I set it to auto-merge yesterday and went to sleep but the pipeline failed, so I need to fix it.

Just to confirm: the only modes it supports are `off` and `auto`. In matter if supporting `auto` I have to support `cooling` and `heating`, too. Does that make sense with your device?

**Comment by KipK** [comment]
Could you also add thermostatRunningMode ( or thermostatRunningState haven't found the difference in matter doc ) 
This will allow to display that the device is actually active . For now on google home, thermostatas are displayed in grey when running instead of yellow. 

Some other interesting thermostat matter clusters that could be added:

MinHeatSetpointLimit
MaxHeatSetpointLimit
MinCoolSetpointLimit
MaxCoolSetpointLimit

( this should limit the temperature range on the thermostat UI )

Too bad it doesn't seems there is a Presets cluster on current matter implementation on what I've read [ in the doc. ](https://www.googlenestcommunity.com/t5/Smart-Home-Developer-Forum/Matter-Thermostat-on-Google-Home-App/m-p/437635)
Also no humidity cluster, it was handled by native google home thermostat, but they've missed it on the matter side.

**Comment by phxZ31** [comment]
>Just to confirm: the only modes it supports are off and auto. In matter if supporting auto I have to support cooling and heating, too. Does that make sense with your device?

I am not sure. Since it's a water heater  not actually a climate device, it doesn't have those modes, but maybe that doesn't matter?

To be honest, I am not interested in sharing this device over Matter at this time anyway... A method to simply ignore this or certain other devices to allow me to start the Add-On would be fine for me for the meantime. The old Matter bridge add-on would allow me to exclude devices in the configuration options BEFORE attempting to start the add-on.
