### ISSUE TITLE
Impossible values supplied by outside controller crashing the addon

### ISSUE THREAD

**Issue by Verteo** [t0bst4r/home-assistant-matter-hub#53]
**Disclaimer:** I'm not sure if this classifies as a bug

# Description

In my setup I use Home Assistant + deCONZ to controll my lights and I had problems with certain deCONZ automations crashing HAMH. I could trace it down to deCONZ reporting out range values in groups with mixed types of lights.

I have a group with 4 normal hue bulb and one hue filament bulb and an automation which changes the light temperature from 2000k to 4000k over time. When starting the automation deconz seems to report a value outside the supported range for the filament bulb for a brief moment. This value in turn crashes HAMH, see the log. After this deconz returns the correct value.

The filament supports only the range 2200k-4500k (454-222 mired) unlike the the normal bulbs 2000k-6700k (500-153 mired)

<details>

<summary>Log</summary>

```
[ 2024-11-01T11:32:24.325Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back setStateOf<3a6a1da910ef412699880da833b447c8.aggregator.light_nachttisch_filament>#3174 due to error: Validating 3a6a1da910ef412699880da833b447c8.aggregator.light_nachttisch_filament.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTempPhysicalMaxMireds": Value 153.0221882172915 is not within bounds defined by constraint (135)
[ 2024-11-01T11:32:24.329Z ] [ ERROR ] [ matter.js / Logger                                 ]: Unhandled error detected: Validating 3a6a1da910ef412699880da833b447c8.aggregator.light_nachttisch_filament.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTempPhysicalMaxMireds": Value 153.0221882172915 is not within bounds defined by constraint (135)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/constraint.js:35:17
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:156:25
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:15:22
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/StructManager.js:138:13
  at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:152:7)
  at ColorControl$State.set [as colorTemperatureMireds] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/StructManager.js:108:32)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/ValuePatcher.js:77:21
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/Endpoint.js:190:7
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async LightDevice.setStateOf (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/Endpoint.js:178:5)
file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/constraint.js:35
          throw new ConstraintError(
                ^

ConstraintError: Validating 3a6a1da910ef412699880da833b447c8.aggregator.light_nachttisch_filament.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTempPhysicalMaxMireds": Value 500 is not within bounds defined by constraint (135)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/constraint.js:35:17
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:156:25
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:15:22
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/StructManager.js:138:13
    at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:152:7)
    at ColorControl$State.set [as colorTemperatureMireds] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/StructManager.js:108:32)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/values/ValuePatcher.js:77:21
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/Endpoint.js:190:7
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LightDevice.setStateOf (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/Endpoint.js:178:5) {
  code: 135,
  clusterCode: undefined
}

Node.js v18.20.4
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
</details>

## Steps to reproduce

1. Create a group in deCONZ of light with different capabilities, e.g normal Hue bulb and filament bulb
2. Set the groups color temperature to a value impossible for at least one bulb, e.g 2000k
3. See HAMH crash

## Version
```
 Add-on version: 3.0.0-alpha.13
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.2
 Home Assistant Supervisor: 2024.10.3
```

**Comment by Verteo** [comment]
The crash is gone in 3.0.0-alpha.14. Thanks for the quick fix
