### ISSUE TITLE
Google home cannot dim nor change colour on light bulbs

### ISSUE THREAD

**Issue by MitoKafander** [t0bst4r/home-assistant-matter-hub#59]
When I try to dim the lights in google home I get an error: "An error occurred. Please try again" or "Something went wrong". After that the dimming value returns to what was set before in HA. 

Also when I ask google assistant through a google home mini to adjust the lights dimming it says: "[light name] offline"

When I change the dimming level in HA the correct value can be seen in google home. 

Changing colours in google home does nothing. Almost behaves the same way as with dimming - try to change the colour and the toggling can be seen but it just bounces back. When I change the colour in HA then google home will not reflect that. 

Using IKEA tradfri zigbee bulbs.

**Comment by ThatBlockyPenguin** [comment]
I have the same issue with Philips Hue bulbs - notably I still had this issue on the old addon, based on Matterbridge. I upgraded to this addon in hopes it would fix it, but alas, it looks like it's an issue with Google's Matter implementation :(

**Comment by KipK** [comment]
This is duplicate with #4 
Stable firmware on google home is the same as preview one, so same bug for everybody until google fix this.

[ 2024-11-05T17:22:16.744Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back online#73a2950@88f90ed3 due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask
[ 2024-11-05T17:22:16.744Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask in field optionsMask

**Comment by MitoKafander** [comment]
Hi!

Can confirm that dimming now works in Current version: 3.0.0-alpha.19.
```
[ 2024-11-06T20:52:41.814Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_2.levelControl.moveToLevelWithOnOff online#ec26007@f78bad57 level: 127 transitionTime: null optionsMask: { executeIfOff: false, coupleColorTempToLevel: false } optionsOverride: { executeIfOff: false, coupleColorTempToLevel: false }
[ 2024-11-06T20:52:41.818Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_1.levelControl.moveToLevelWithOnOff online#ec26008@f78bad57 level: 127 transitionTime: null optionsMask: { executeIfOff: false, coupleColorTempToLevel: false } optionsOverride: { executeIfOff: false, coupleColorTempToLevel: false }
```

Also colour changing works.
```
[ 2024-11-06T20:53:33.419Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_2.colorControl.moveToHueAndSaturation online#ec2601e@f78bad57 hue: 169 saturation: 254 transitionTime: 2 optionsMask: { executeIfOff: true } optionsOverride: { executeIfOff: true }
[ 2024-11-06T20:53:33.422Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_1.colorControl.moveToHueAndSaturation online#ec2601f@f78bad57 hue: 169 saturation: 254 transitionTime: 2 optionsMask: { executeIfOff: true } optionsOverride: { executeIfOff: true }
[ 2024-11-06T20:53:33.425Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_2.onOff.on online#ec26020@f78bad57 (no payload)
[ 2024-11-06T20:53:33.427Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_1.onOff.on online#ec26021@f78bad57 (no payload)
[ 2024-11-06T20:53:33.530Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_2.homeAssistant.state: Referencing e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_2.levelControl.state: This value is no longer available because its context has exited (1)
  at get value [as value] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:122:15)
  at descriptor.get [as config] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:150:49)
  at _LevelControlServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1289:34)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1285:44
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:101:22
[ 2024-11-06T20:53:33.574Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_1.homeAssistant.state: Referencing e717607b77f74e7fa6a00b3c3ad6bdd5.aggregator.light_office_light_1.levelControl.state: This value is no longer available because its context has exited (1)
  at get value [as value] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:122:15)
  at descriptor.get [as config] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:150:49)
  at _LevelControlServer.update (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1289:34)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1285:44
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:101:22
```

**Comment by KipK** [comment]
Yeah good news. It works now with latest update.

**Comment by t0bst4r** [comment]
Nice!
The level control bug is fixed with alpha.20 and later 😃
