### ISSUE TITLE
[Bug] Entity name length causes crash

### ISSUE THREAD

**Issue by stewe93** [t0bst4r/home-assistant-matter-hub#6]
So I'm trying to test the app but after adding the first bridge I got the following error: 
```
[ 2024-10-27T19:54:20.502Z ] [ INFO  ] [ Storage                                  ]: Storage location: /data
[ 2024-10-27T19:54:20.535Z ] [ INFO  ] [ WebApi                                   ]: HTTP server (API & Web App) listening on port 8482
[ 2024-10-27T19:56:32.972Z ] [ INFO  ] [ matter.js / ServerStore                  ]: Opened 572cc88a0f2f468da23e4fa08e628f8f storage at /data/572cc88a0f2f468da23e4fa08e628f8f
[ 2024-10-27T19:56:33.198Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 572cc88a0f2f468da23e4fa08e628f8f ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions ✔descriptor
[ 2024-10-27T19:56:33.203Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 572cc88a0f2f468da23e4fa08e628f8f.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✔index ✔descriptor
[ 2024-10-27T19:56:33.216Z ] [ INFO  ] [ matter.js / Node                         ]: 572cc88a0f2f468da23e4fa08e628f8f going online
[ 2024-10-27T19:56:33.376Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back initialize<572cc88a0f2f468da23e4fa08e628f8f.aggregator.light_household_room_washing_machine_indicator_light_light>#1c due to error: Behaviors have errors
[ 2024-10-27T19:56:33.394Z ] [ ERROR ] [ matter.js / Logger                       ]: Unhandled error detected: Behaviors have errors
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/endpoint/properties/Behaviors.js:122:21
  at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:375:17)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/util/Construction.js:365:11
  Cause #0: Error initializing 572cc88a0f2f468da23e4fa08e628f8f.aggregator.light_household_room_washing_machine_indicator_light_light.bridgedDeviceBasicInformation
    at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/BehaviorBacking.js:52:13)
  Caused by: Validating 572cc88a0f2f468da23e4fa08e628f8f.aggregator.light_household_room_washing_machine_indicator_light_light.bridgedDeviceBasicInformation.state.nodeLabel: Constraint "all": Lenght of value Household Room indicator light Light is not within bounds defined by constraint (135)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/constraint.js:54:17
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:156:25
    at Object.nodeLabel (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/conformance.js:15:22)
    at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/validation/ValueValidator.js:191:23)
    at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/state/managed/Datasource.js:38:7)
    at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/internal/ServerBacking.js:29:23)
```

Bridge config: 
```json
{
  "name": "matterhub",
  "port": 5540,
  "filter": {
    "include": [
      { "type": "domain", "value": "light" }
    ],
    "exclude": []
  }
}
```

As I can see from the logs, the entity's name is too long and that's why it crashed, would you handle this situation or I should shorten the name of the entity?

**Comment by t0bst4r** [comment]
That’s a good question. I will probably add a function to cut after x characters, but then you‘ll have an incomplete name in your voice assistant.
