### ISSUE TITLE
Current version: 3.0.0-alpha.17 

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/home-assistant-matter-hub#62]
d0a41b0a2e284c31b3377d85d90af3fe.aggregator.binary_sensor_bedroom_bathroom_door_opening ready endpoint#: 11 type: ContactSensor (0x15) behaviors: ✔identify ✔booleanState ✔bridgedDeviceBasicInformation ✔descriptor
home-assistant-matter-hub start

start the application

Options:
  --help                         Show help                             [boolean]
  --log-level
  [string] [choices: "silly", "debug", "info", "warn", "error"] [default: "info"
                                                                               ]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --mdns-network-interface       Limit MDNS to this network interface   [string]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]

TypeError: Cannot read properties of undefined (reading 'endpoint')
    at get endpoint (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/Behavior.js:53:24)
    at get endpoint [as endpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:996:20)
    at new HaMixin (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:990:14)
    at new ThermostatBaseServer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2309:10)
    at new _HeatingAndCoolingThermostatServerBase (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2450:45)
    at introspectionInstanceOf (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:16:10)
    at createDefaultCommandDescriptors (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:192:20)
    at createType (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:59:26)
    at _HeatingAndCoolingThermostatServerBase.for (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehavior.js:65:12)
    at _HeatingAndCoolingThermostatServerBase.with (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehavior.js:72:20)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by GiacomoST** [comment]
Same problem

**Comment by jesusgcas** [comment]
Same
