### ISSUE TITLE
[Bug] HAMH-alpha 17 won't start

### ISSUE THREAD

**Issue by phxZ31** [t0bst4r/home-assistant-matter-hub#63]
Just tried the latest version (alpha 17) hoping that I could get it to start, but still no luck.
Here's the log output: 

```
>s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
>
>-----------------------------------------------------------
> Add-on: Home-Assistant-Matter-Hub
> Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
>-----------------------------------------------------------
> Add-on version: 3.0.0-alpha.17
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.10.4
> Home Assistant Supervisor: 2024.10.3
>-----------------------------------------------------------
> Please, share the above information when looking for help
> or support in, e.g., GitHub, forums or the Discord chat.
>-----------------------------------------------------------
>s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-11-03T17:09:44.796Z ] [ INFO  ] [ Storage                                            ]: Storage location: /config/data
[ 2024-11-03T17:09:45.090Z ] [ INFO  ] [ matter.js / ServerStore                            ]: Opened 8806d8e6953e4104a68c45e236ce73f5 storage at /config/data/8806d8e6953e4104a68c45e236ce73f5
[ 2024-11-03T17:09:46.376Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions ✔descriptor
[ 2024-11-03T17:09:46.404Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✔index ✔descriptor
[ 2024-11-03T17:09:46.424Z ] [ INFO  ] [ matter.js / Node                                   ]: 8806d8e6953e4104a68c45e236ce73f5 going online
[ 2024-11-03T17:09:46.777Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.binary_sensor_rpi_power_status ready endpoint#: 2 type: ContactSensor (0x15) behaviors: ✔identify ✔booleanState ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-03T17:09:46.871Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.sensor_econet_etwh_lower_tank_temperature ready endpoint#: 3 type: TemperatureSensor (0x302) behaviors: ✔temperatureMeasurement ✔identify ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-03T17:09:46.914Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.sensor_econet_etwh_upper_tank_temperature ready endpoint#: 4 type: TemperatureSensor (0x302) behaviors: ✔temperatureMeasurement ✔identify ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-03T17:09:47.076Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_beep_on_alarm ready endpoint#: 5 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-03T17:09:47.129Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_screen_adjustment_lock ready endpoint#: 6 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-11-03T17:09:47.174Z ] [ INFO  ] [ matter.js / Endpoint                               ]: 8806d8e6953e4104a68c45e236ce73f5.aggregator.switch_econet_etwh_screen_unit_in_c ready endpoint#: 7 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
>home-assistant-matter-hub start
>
>start the application
>
>Options:
  --help                         Show help                             [boolean]
  --log-level
  [string] [choices: "silly", "debug", "info", "warn", "error"] [default: "info"
                                                                               ]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --mdns-network-interface       Limit MDNS to this network interface   [string]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]
>
>TypeError: Cannot read properties of undefined (reading 'endpoint')
    at get endpoint (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/Behavior.js:53:24)
    at get endpoint [as endpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:996:20)
    at new HaMixin (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:990:14)
    at new ThermostatBaseServer (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2309:10)
    at new _HeatingAndCoolingThermostatServerBase (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2450:45)
    at introspectionInstanceOf (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:16:10)
    at createDefaultCommandDescriptors (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:192:20)
    at createType (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehaviorUtil.js:59:26)
    at _HeatingAndCoolingThermostatServerBase.for (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehavior.js:65:12)
    at _HeatingAndCoolingThermostatServerBase.with (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/behavior/cluster/ClusterBehavior.js:72:20)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by jesusgcas** [comment]
Thanks, you are right. For me stopped working after updating from 15 to 17 but after removing a clima device at least I can start the hub.

**Comment by phxZ31** [comment]
>but after removing a clima device at least I can start the hub.

Did I miss something? Is there a configuration file I can edit to make HAMH ignore this device?

**Comment by t0bst4r** [comment]
sorry. i was knocked out with covid for some days and slowly recovering.
i'll release a fix today

**Comment by t0bst4r** [comment]
just released `alpha.18` which fixes the bug by ignoring climates which do not have cooling and heating, but only auto. this will be fixed later on.
