### ISSUE TITLE
[Bug] Unexpected end of JSON input

### ISSUE THREAD

**Issue by nehasjains** [t0bst4r/home-assistant-matter-hub#9]
Below is the log output

```
Options:
  --help                         Show help                             [boolean]
  --log-level
          [string] [choices: "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/storage/StringifyTools.js:40:15)
    at StorageBackendJsonFile.fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter-node.js/dist/esm/storage/StorageBackendJsonFile.js:90:12)
    at StorageBackendJsonFile.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter-node.js/dist/esm/storage/StorageBackendJsonFile.js:38:25)
    at async StorageService.open (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/environment/StorageService.js:31:5)
    at async handler (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3271:19)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Home-Assistant-Matter-Hub
 Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
-----------------------------------------------------------
 Add-on version: 3.0.0-alpha.7
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-10-28T01:59:35.558Z ] [ INFO  ] [ Storage                                  ]: Storage location: /config/data
home-assistant-matter-hub start

start the application

Options:
  --help                         Show help                             [boolean]
  --log-level
          [string] [choices: "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/storage/StringifyTools.js:40:15)
    at StorageBackendJsonFile.fromJson (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter-node.js/dist/esm/storage/StorageBackendJsonFile.js:90:12)
    at StorageBackendJsonFile.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter-node.js/dist/esm/storage/StorageBackendJsonFile.js:38:25)
    at async StorageService.open (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@project-chip/matter.js/dist/esm/environment/StorageService.js:31:5)
    at async handler (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3271:19)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by nehasjains** [comment]
I tried reinstalling the addon. Restarted homeassistant.  But still the addon is crashing.

**Comment by t0bst4r** [comment]
Do you have access to the addon files (e.g. by using the file browser addon) ?

If yes, could you please open the addon directory and tell me what’s in there? There should be a `data` (or `config/data`) folder, which includes some json files. 
I expect one of them to be empty and therefore not being valid json. If its empty anyway you can simply delete it without any losses. But please tell me which file, if any.

**Comment by nehasjains** [comment]
There is a json file called app.json. This file was blank. I deleted the file, restarted the addon. The addon started. I was able to see the web ui.

I clocked on the + icon to create a bridge, gave the bridge a name and clicked Create. It gave error "load failed". And the addon keep on crashing again.

**Comment by nehasjains** [comment]
As the entity switch_my_cam_lens_distortion_correction is causing the crash at the moment. Please see below, is this the correct way to exclude that entity? I have tried this but still giving the same error.

{
  "name": "Testing",
  "port": 5540,
  "filter": {
    "include": [
      {"type": "domain", "value": "light"},
      {"type": "domain", "value": "switch"}
    ],
    "exclude": [
      {"type": "pattern", "value": "switch.my_cam_lens_distortion_correction"}
    ]
  }
}

**Comment by t0bst4r** [comment]
Does the app start at all?
You could try deleting all the files in the data directory and then restart from scratch by excluding the entity.

I will take care of the name length in #6 
Please give it a thumbs up to increase priority 😉

Anyway I need to stabilize the app regarding invalid configs and/or invalid devices (e.g. caused by the name).

**Comment by nehasjains** [comment]
Yes, the app starts after deleting the json file. It's crashing because of the length of the entity name.

Looking forward for the update.

**Comment by t0bst4r** [comment]
So the exclusion does not work?

**Comment by nehasjains** [comment]
> So the exclusion does not work?

No it doesn't.

**Comment by levanLuongnt** [comment]
[ 2024-10-28T09:39:08.483Z ] [ ERROR ] [ matter.js / Logger                       ]: Unhandled error detected: Cannot read properties of undefined (reading 'state')
  at _OnOffServer.createState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1090:24)
  at new SwitchDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1561:32)
  at switch (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2665:25)
  at createDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2644:10)
  at Bridge.createDevices (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2737:26)
  at async Bridge.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2729:9)
  at async BridgeService.create (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2826:9)
  at async file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:698:24
file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1090
          onOff: state.state !== "off"
                       ^

TypeError: Cannot read properties of undefined (reading 'state')

**Comment by nehasjains** [comment]
Just wait for the next alpha. I guess most of these errors/bugs will be fixed.

**Comment by joacim69** [comment]
Yeah, I can't even find the folder with the json file, so it's nice to know it's nothing to do but wait for the next file. Thanks https://github.com/t0bst4r for your hard work!

**Comment by t0bst4r** [comment]
just merged a bug fix. release is in progress and will be available in a few minutes.
