### ISSUE TITLE
[BUG] alpha24 crash - looks to be light related

### ISSUE THREAD

**Issue by DJBenson** [t0bst4r/home-assistant-matter-hub#99]
Updated to the new alpha hoping my thermostats would work and the bridge no longer starts due to the error below. No changes to devices between alpha 23 and 24.
```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 02ef6e4c0bdf4eb8a78a85f442104c61.aggregator.light_dining_room_lights.colorControl
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 02ef6e4c0bdf4eb8a78a85f442104c61.aggregator.light_dining_room_lights.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTemperatureMireds": Value 154 is not within bounds defined by constraint (135)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/constraint.js:35:17
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:154:25
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:15:22
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at ColorControl$State.set [as coupleColorTempToLevelMinMireds] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at _ExtendedColorControlServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1200:52)
```

**Comment by t0bst4r** [comment]
i changed the way i am rounding those min and max values. i hope this should be fixed now. if not feel free to reopen this issue.

**Comment by DJBenson** [comment]
Getting a new crash now. Will raise a new bug.

**Comment by DJBenson** [comment]
Someone else already raised it #103.
